/**
 * 智能体对话相关类型定义
 * 遵循单一职责原则，每个接口只描述一个领域概念
 */

// ============ 工作流状态 ============
export type WorkflowState =
  | 'IDLE'
  | 'FETCHING_STEPS'
  | 'FETCHING_FIRST_STEP'
  | 'RUNNING_CARD'
  | 'CHATTING'
  | 'COMPLETED'
  | 'ERROR';

// ============ 消息相关 ============
export type MessageRole = 'user' | 'assistant' | 'system';

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
}

// ============ 会话相关 ============
export interface AgentSession {
  trainTaskId: string;
  sessionId: string | null;
  currentStepId: string | null;
  workflowState: WorkflowState;
  dialogueRound: number;
  lastUpdated: number;
}

// ============ 认证相关 ============
export interface AuthInfo {
  authorization: string | null;
  cookies: string;
}

// ============ API响应类型 ============
export interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

export interface ScriptStep {
  id: string;
  stepName: string;
  stepOrder: number;
  scriptId: string;
}

export interface ScriptStepFlow {
  id: string;
  stepId: string;
  flowOrder: number;
  content: string;
}

export interface RunCardResponse {
  sessionId: string;
  stepId: string;
  content: string;
}

export interface ChatResponse {
  content: string;
  isCompleted: boolean;
  nextStepId?: string;
}

// ============ Background消息类型 ============
export type BackgroundMessageType =
  | 'GET_CURRENT_TAB_URL'
  | 'GET_AUTH'
  | 'EXTRACT_TRAIN_TASK_ID'
  | 'API_REQUEST';

export interface BackgroundMessage<T = unknown> {
  type: BackgroundMessageType;
  payload?: T;
}

export interface BackgroundResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

// ============ API请求负载 ============
export interface ApiRequestPayload {
  endpoint: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  body?: Record<string, unknown>;
  headers?: Record<string, string>;
}

// ============ 步骤列表请求/响应 ============
export interface QueryScriptStepListRequest {
  trainTaskId: string;
}

export interface QueryScriptStepFlowListRequest {
  stepId: string;
}

export interface RunCardRequest {
  trainTaskId: string;
  stepId: string;
}

export interface ChatRequest {
  sessionId: string;
  content: string;
  isAutoGenerated?: boolean;
}
