/**
 * 智能体对话Hook
 * 管理对话状态和工作流
 */

import {
  apiRequest,
  extractTrainTaskId,
  getCurrentTabUrl,
  onTabUrlChanged,
  API_ENDPOINTS,
} from '../services/background-bridge';
import { generateStudentAnswer } from '../services/llm-service';
import { resolveTrainingMetadata } from '../services/training-metadata-service';
import { agentLogStorage, agentSessionStorage, llmConfigStorage } from '@extension/storage';
import { useState, useCallback, useEffect, useRef } from 'react';
import type { AgentLogEntry } from '@extension/storage';

// ============ 类型定义 ============
type WorkflowState =
  | 'IDLE'
  | 'FETCHING_STEPS'
  | 'FETCHING_FIRST_STEP'
  | 'RUNNING_CARD'
  | 'CHATTING'
  | 'COMPLETED'
  | 'ERROR';

type MessageRole = 'user' | 'assistant' | 'system';

interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
  modelId?: string;
}

interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

type ScriptNodeType = 'SCRIPT_START' | 'SCRIPT_END' | 'SCRIPT_NODE';

// API 返回的步骤列表项结构（参考 Python: workflow_tester_base.py）
interface ScriptStepItem {
  stepId: string; // 步骤ID（用于 runCard）
  stepDetailDTO?: {
    stepName?: string;
    stepOrder?: number;
    nodeType?: ScriptNodeType;
  };
}

// 用于 queryScriptStepFlowList 的结构
interface ScriptStepFlow {
  scriptStepStartId: string;
  scriptStepEndId: string; // 第一个真实步骤的ID
  isDefault?: number;
}

interface TrainConfigurationResponse {
  trainTaskName?: string;
}

interface RunCardResponse {
  sessionId: string;
  text?: string; // Python 代码中用的是 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
}

interface ChatResponse {
  text?: string; // Python 代码中用的是 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
  // 结束判断：当 text 和 nextStepId 都为 null 时表示完成
}

const TRAINING_DOMAIN = 'hike-teaching-center.polymas.com';

// ============ Hook实现 ============
const useAgentChat = () => {
  // 状态
  const [trainTaskId, setTrainTaskId] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [currentStepId, setCurrentStepId] = useState<string | null>(null);
  const [workflowState, setWorkflowState] = useState<WorkflowState>('IDLE');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dialogueRound, setDialogueRound] = useState(0);
  const [isAutoRunning, setIsAutoRunning] = useState(false);
  const [activeLogSessionId, setActiveLogSessionId] = useState<string | null>(null);
  const [scriptSteps, setScriptSteps] = useState<ScriptStepItem[]>([]);
  const [isStepListLoading, setIsStepListLoading] = useState(false);
  const [stepListError, setStepListError] = useState<string | null>(null);

  // 用于取消请求
  const abortControllerRef = useRef<AbortController | null>(null);
  const autoRunActiveRef = useRef(false);
  const autoRunTokenRef = useRef(0);
  const messagesRef = useRef<ChatMessage[]>([]);
  const workflowStateRef = useRef<WorkflowState>('IDLE');
  const isLoadingRef = useRef(false);
  const sessionIdRef = useRef<string | null>(null);
  const currentStepIdRef = useRef<string | null>(null);
  const trainTaskIdRef = useRef<string | null>(null);
  const dialogueRoundRef = useRef(0);
  const activeLogSessionIdRef = useRef<string | null>(null);
  const stepNameMappingRef = useRef<Record<string, string>>({});
  const stepNodeTypeByIdRef = useRef<Record<string, ScriptNodeType>>({});
  const scriptStepsRef = useRef<ScriptStepItem[]>([]);

  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  useEffect(() => {
    workflowStateRef.current = workflowState;
  }, [workflowState]);

  useEffect(() => {
    isLoadingRef.current = isLoading;
  }, [isLoading]);

  useEffect(() => {
    sessionIdRef.current = sessionId;
  }, [sessionId]);

  useEffect(() => {
    currentStepIdRef.current = currentStepId;
  }, [currentStepId]);

  useEffect(() => {
    trainTaskIdRef.current = trainTaskId;
  }, [trainTaskId]);

  useEffect(() => {
    dialogueRoundRef.current = dialogueRound;
  }, [dialogueRound]);

  useEffect(() => {
    activeLogSessionIdRef.current = activeLogSessionId;
  }, [activeLogSessionId]);

  useEffect(() => {
    scriptStepsRef.current = scriptSteps;
  }, [scriptSteps]);

  const fetchTrainTaskName = useCallback(async (taskId: string): Promise<string | undefined> => {
    try {
      const configResponse = await apiRequest<ApiResponse<TrainConfigurationResponse>>({
        endpoint: API_ENDPOINTS.QUERY_CONFIGURATION,
        method: 'POST',
        body: { trainTaskId: taskId },
      });
      return configResponse?.data?.trainTaskName;
    } catch (error) {
      console.warn('⚠️ 获取训练任务名称失败:', error);
      return undefined;
    }
  }, []);
  const updateStoredTrainTaskId = useCallback(async (taskId: string) => {
    try {
      await agentSessionStorage.updateTrainTaskId(taskId);
    } catch (storageError) {
      console.warn('⚠️ 训练任务ID缓存失败:', storageError);
    }
  }, []);

  const getStepDisplayName = useCallback((stepId: string) => stepNameMappingRef.current[stepId] ?? stepId, []);
  const resolveCurrentProfileLabel = useCallback(async () => {
    const config = await llmConfigStorage.get();
    const selected = config.studentProfiles.find(profile => profile.id === config.studentProfileId);
    const fallback = config.studentProfiles[0];
    const label = (selected ?? fallback)?.label?.trim();
    return label && label.length > 0 ? label : '学生';
  }, []);

  const buildLogSessionName = useCallback((baseName: string, profileLabel: string) => {
    const parts = [baseName, profileLabel, '剧本'].filter(Boolean);
    return `${parts.join('-')}`;
  }, []);

  const buildStepNameMapping = useCallback((steps: ScriptStepItem[]) => {
    const stepNameMapping: Record<string, string> = {};
    steps.forEach(step => {
      if (step.stepDetailDTO?.stepName) {
        stepNameMapping[step.stepId] = step.stepDetailDTO.stepName;
      }
    });
    stepNameMappingRef.current = stepNameMapping;
    return stepNameMapping;
  }, []);

  const buildStepNodeTypeMapping = useCallback((steps: ScriptStepItem[]) => {
    const mapping: Record<string, ScriptNodeType> = {};
    steps.forEach(step => {
      const nodeType = step.stepDetailDTO?.nodeType;
      if (nodeType) {
        mapping[step.stepId] = nodeType;
      }
    });
    stepNodeTypeByIdRef.current = mapping;
    return mapping;
  }, []);

  // 生成消息ID
  const generateMessageId = useCallback(() => `msg_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`, []);

  // 添加消息
  const addMessage = useCallback(
    (role: MessageRole, content: string, isAutoGenerated = false, stepIdOverride?: string, modelId?: string) => {
      const message: ChatMessage = {
        id: generateMessageId(),
        role,
        content,
        timestamp: Date.now(),
        stepId: stepIdOverride ?? currentStepId ?? undefined,
        isAutoGenerated,
        modelId,
      };
      setMessages(prev => [...prev, message]);
      return message;
    },
    [generateMessageId, currentStepId],
  );

  const isTerminalStep = useCallback((stepId: string) => stepNodeTypeByIdRef.current[stepId] === 'SCRIPT_END', []);
  const completeTraining = useCallback(() => {
    setWorkflowState('COMPLETED');
    addMessage('system', '✅ 恭喜！训练已完成！');
  }, [addMessage]);

  const appendLogEntry = useCallback(async (entry: AgentLogEntry) => {
    const sessionId = activeLogSessionIdRef.current;
    if (!sessionId) {
      return;
    }
    await agentLogStorage.addEntry(sessionId, entry);
  }, []);

  const announceNextStep = useCallback(
    (stepId: string) => {
      const stepName = getStepDisplayName(stepId);
      addMessage('system', `进入下一个阶段——${stepName}`, false, stepId);
    },
    [addMessage, getStepDisplayName],
  );

  const runCardForStep = useCallback(
    async (stepId: string, sessionOverride?: string | null): Promise<ApiResponse<RunCardResponse> | null> => {
      if (!trainTaskId) {
        throw new Error('未找到训练任务ID');
      }

      // SCRIPT_END 终止节点直接结束，不再请求 runCard
      if (isTerminalStep(stepId)) {
        setCurrentStepId(stepId);
        currentStepIdRef.current = stepId;
        completeTraining();
        return null;
      }

      setWorkflowState('RUNNING_CARD');

      const runCardResponse = await apiRequest<ApiResponse<RunCardResponse>>({
        endpoint: API_ENDPOINTS.RUN_CARD,
        method: 'POST',
        body: {
          taskId: trainTaskId,
          stepId,
          sessionId: sessionOverride ?? sessionId ?? undefined,
        },
      });

      console.log('🎴 RunCard Response:', JSON.stringify(runCardResponse, null, 2));

      if (!runCardResponse?.data?.sessionId) {
        console.error('❌ sessionId 未找到，完整响应:', runCardResponse);
        throw new Error('启动对话失败');
      }

      setSessionId(runCardResponse.data.sessionId);
      sessionIdRef.current = runCardResponse.data.sessionId;
      setCurrentStepId(stepId);
      currentStepIdRef.current = stepId;
      setWorkflowState('CHATTING');

      if (runCardResponse.data.text) {
        addMessage('assistant', runCardResponse.data.text, false, stepId);
        await appendLogEntry({
          type: 'chat',
          timestamp: Date.now(),
          stepId,
          stepName: getStepDisplayName(stepId),
          round: dialogueRoundRef.current,
          source: 'runCard',
          aiText: runCardResponse.data.text,
        });
      }

      if (runCardResponse.data.needSkipStep && runCardResponse.data.nextStepId) {
        const nextStepId = runCardResponse.data.nextStepId;
        setCurrentStepId(nextStepId);
        currentStepIdRef.current = nextStepId;
        if (isTerminalStep(nextStepId)) {
          completeTraining();
          return runCardResponse;
        }
        announceNextStep(nextStepId);
        return runCardForStep(nextStepId, runCardResponse.data.sessionId);
      }

      return runCardResponse;
    },
    [
      trainTaskId,
      sessionId,
      addMessage,
      appendLogEntry,
      getStepDisplayName,
      announceNextStep,
      isTerminalStep,
      completeTraining,
    ],
  );

  // 初始化 - 从URL提取trainTaskId
  const initialize = useCallback(async () => {
    const taskId = await extractTrainTaskId();
    if (taskId) {
      const taskName = await fetchTrainTaskName(taskId);
      setTrainTaskId(taskId);
      await updateStoredTrainTaskId(taskId);
      const displayName = taskName?.trim() || `${taskId.substring(0, 8)}...`;
      addMessage('system', `已检测到训练任务: ${displayName}`);
      return;
    }

    const currentUrl = await getCurrentTabUrl();
    if (!currentUrl?.includes(TRAINING_DOMAIN)) {
      return;
    }

    try {
      const storedSession = await agentSessionStorage.get();
      const storedTaskId = storedSession.trainTaskId?.trim();
      if (storedTaskId) {
        const taskName = await fetchTrainTaskName(storedTaskId);
        setTrainTaskId(storedTaskId);
        const displayName = taskName?.trim() || `${storedTaskId.substring(0, 8)}...`;
        addMessage('system', `已从缓存恢复训练任务: ${displayName}`);
      }
    } catch (storageError) {
      console.warn('⚠️ 读取训练任务缓存失败:', storageError);
    }
  }, [addMessage, fetchTrainTaskName, updateStoredTrainTaskId]);

  const fetchScriptSteps = useCallback(
    async ({
      force = false,
      announce = false,
    }: {
      force?: boolean;
      announce?: boolean;
    } = {}): Promise<ScriptStepItem[]> => {
      if (!trainTaskId) {
        const message = '未找到训练任务ID';
        setStepListError(message);
        if (announce) {
          addMessage('system', message);
        }
        return [];
      }

      if (!force && scriptStepsRef.current.length > 0) {
        return scriptStepsRef.current;
      }

      setStepListError(null);
      setIsStepListLoading(true);

      try {
        const stepsResponse = await apiRequest<ApiResponse<ScriptStepItem[]>>({
          endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_LIST,
          method: 'POST',
          body: { trainTaskId, trainSubType: 'ability' },
        });

        if (!stepsResponse?.data?.length) {
          throw new Error('获取步骤列表失败');
        }

        const steps = stepsResponse.data;
        setScriptSteps(steps);
        scriptStepsRef.current = steps;
        buildStepNameMapping(steps);
        buildStepNodeTypeMapping(steps);
        return steps;
      } catch (err) {
        const message = (err as Error).message || '获取步骤列表失败';
        setStepListError(message);
        if (announce) {
          addMessage('system', `错误: ${message}`);
        }
        return [];
      } finally {
        setIsStepListLoading(false);
      }
    },
    [addMessage, buildStepNameMapping, buildStepNodeTypeMapping, trainTaskId],
  );

  // 监听URL变化
  useEffect(() => {
    initialize();

    const unsubscribe = onTabUrlChanged(async url => {
      if (url.includes('trainTaskId=')) {
        const taskId = await extractTrainTaskId(url);
        if (taskId && taskId !== trainTaskId) {
          const taskName = await fetchTrainTaskName(taskId);
          setTrainTaskId(taskId);
          await updateStoredTrainTaskId(taskId);
          // 重置状态
          setSessionId(null);
          setCurrentStepId(null);
          setWorkflowState('IDLE');
          setMessages([]);
          setDialogueRound(0);
          setActiveLogSessionId(null);
          activeLogSessionIdRef.current = null;
          stepNameMappingRef.current = {};
          stepNodeTypeByIdRef.current = {};
          setScriptSteps([]);
          scriptStepsRef.current = [];
          setStepListError(null);
          setIsStepListLoading(false);
          const displayName = taskName?.trim() || `${taskId.substring(0, 8)}...`;
          addMessage('system', `已切换到新任务: ${displayName}`);
        }
      }
    });

    return unsubscribe;
  }, [initialize, trainTaskId, addMessage, fetchTrainTaskName, updateStoredTrainTaskId]);

  // 开始对话流程
  const startConversation = useCallback(async () => {
    if (!trainTaskId) {
      setError('未找到训练任务ID，请确保在正确的页面打开');
      return;
    }

    setError(null);
    setIsLoading(true);

    try {
      // 步骤1: 获取任务配置（用于日志命名）
      const [taskName, profileLabel, trainingMeta] = await Promise.all([
        fetchTrainTaskName(trainTaskId),
        resolveCurrentProfileLabel(),
        resolveTrainingMetadata(),
      ]);
      const displayName = taskName?.trim() || `${trainTaskId.substring(0, 8)}...`;
      const logSessionName = buildLogSessionName(displayName, profileLabel);

      // 步骤2: 获取步骤列表
      setWorkflowState('FETCHING_STEPS');
      addMessage('system', '正在获取训练步骤...');

      const steps = await fetchScriptSteps({ force: true });
      if (!steps.length) {
        throw new Error('获取步骤列表失败');
      }

      console.log('📋 First Step:', JSON.stringify(steps[0], null, 2));

      try {
        const newSession = await agentLogStorage.createSession({
          taskId: trainTaskId,
          taskName: logSessionName,
          trainingMeta,
          stepNameMapping: stepNameMappingRef.current,
        });
        setActiveLogSessionId(newSession.id);
        activeLogSessionIdRef.current = newSession.id;
      } catch (logError) {
        console.warn('⚠️ 日志初始化失败:', logError);
      }

      // 优先通过 SCRIPT_START + flowList 获取第一个真实步骤
      let firstStepId: string | null = null;
      let firstStepName = '未知步骤';
      const trainingStartStep =
        steps.slice(0, 2).find(step => step.stepDetailDTO?.nodeType === 'SCRIPT_START') ??
        steps.find(step => step.stepDetailDTO?.nodeType === 'SCRIPT_START');
      const trainingStartStepId = trainingStartStep?.stepId ?? null;

      try {
        const flowResponse = await apiRequest<ApiResponse<ScriptStepFlow[]>>({
          endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_FLOW_LIST,
          method: 'POST',
          body: { trainTaskId },
        });
        console.log('🔗 Flow Response:', JSON.stringify(flowResponse, null, 2));

        if (flowResponse?.data?.length && trainingStartStepId) {
          const matchedFlow =
            flowResponse.data.find(flow => flow.scriptStepStartId === trainingStartStepId && flow.isDefault === 1) ??
            flowResponse.data.find(flow => flow.scriptStepStartId === trainingStartStepId);
          firstStepId = matchedFlow?.scriptStepEndId ?? null;
        }
      } catch {
        console.warn('⚠️ flowList 获取失败，使用回退逻辑');
      }

      // 回退逻辑：如果 flowList 失败，优先取非 SCRIPT_START/SCRIPT_END 的步骤
      if (!firstStepId) {
        const fallbackStep =
          steps.find(step => {
            const nodeType = step.stepDetailDTO?.nodeType;
            return nodeType && nodeType !== 'SCRIPT_START' && nodeType !== 'SCRIPT_END';
          }) ?? steps[steps.length > 2 ? 2 : 0];
        firstStepId = fallbackStep?.stepId ?? null;
      }

      if (!firstStepId) {
        throw new Error('无法确定首个训练步骤');
      }

      const matchedStep = steps.find(s => s.stepId === firstStepId);
      if (matchedStep?.stepDetailDTO?.stepName) {
        firstStepName = matchedStep.stepDetailDTO.stepName;
      }

      setCurrentStepId(firstStepId);
      currentStepIdRef.current = firstStepId;

      // 步骤2: 启动卡片
      addMessage('system', `正在启动步骤: ${firstStepName}...`);

      const runCardResult = await runCardForStep(firstStepId);
      if (runCardResult === null) {
        return;
      }
      setDialogueRound(1);

      addMessage('system', '对话已开始，请输入你的回答或点击AI自动回答');
    } catch (err) {
      setWorkflowState('ERROR');
      setError((err as Error).message);
      addMessage('system', `错误: ${(err as Error).message}`);
    } finally {
      setIsLoading(false);
    }
  }, [
    trainTaskId,
    addMessage,
    runCardForStep,
    fetchTrainTaskName,
    resolveCurrentProfileLabel,
    buildLogSessionName,
    fetchScriptSteps,
  ]);

  const stopAutoRun = useCallback(() => {
    if (!autoRunActiveRef.current) {
      return;
    }
    autoRunActiveRef.current = false;
    autoRunTokenRef.current += 1;
    setIsAutoRunning(false);
  }, []);

  const runDebugStep = useCallback(
    async (stepId: string) => {
      if (!trainTaskId) {
        addMessage('system', '未找到训练任务ID');
        return;
      }

      stopAutoRun();
      setError(null);
      setIsLoading(true);

      try {
        const steps =
          scriptStepsRef.current.length > 0 ? scriptStepsRef.current : await fetchScriptSteps({ force: true });
        if (!steps.length) {
          throw new Error('获取步骤列表失败');
        }

        if (!activeLogSessionIdRef.current) {
          const [taskName, profileLabel, trainingMeta] = await Promise.all([
            fetchTrainTaskName(trainTaskId),
            resolveCurrentProfileLabel(),
            resolveTrainingMetadata(),
          ]);
          const displayName = taskName?.trim() || `${trainTaskId.substring(0, 8)}...`;
          const logSessionName = buildLogSessionName(displayName, profileLabel);

          try {
            const newSession = await agentLogStorage.createSession({
              taskId: trainTaskId,
              taskName: logSessionName,
              trainingMeta,
              stepNameMapping: stepNameMappingRef.current,
            });
            setActiveLogSessionId(newSession.id);
            activeLogSessionIdRef.current = newSession.id;
          } catch (logError) {
            console.warn('⚠️ 日志初始化失败:', logError);
          }
        }

        const stepName = getStepDisplayName(stepId);
        addMessage('system', `调试模式：切换到步骤 ${stepName}`);
        const runCardResult = await runCardForStep(stepId, sessionIdRef.current);
        if (runCardResult === null) {
          return;
        }
        setDialogueRound(prev => (prev === 0 ? 1 : prev));
      } catch (err) {
        setWorkflowState('ERROR');
        setError((err as Error).message);
        addMessage('system', `调试失败: ${(err as Error).message}`);
      } finally {
        setIsLoading(false);
      }
    },
    [
      trainTaskId,
      addMessage,
      stopAutoRun,
      fetchScriptSteps,
      fetchTrainTaskName,
      resolveCurrentProfileLabel,
      buildLogSessionName,
      getStepDisplayName,
      runCardForStep,
    ],
  );

  // 发送用户消息
  const sendMessage = useCallback(
    async (content: string) => {
      if (!sessionId || !trainTaskId || !currentStepId || workflowState !== 'CHATTING') {
        return;
      }

      stopAutoRun();
      setIsLoading(true);
      addMessage('user', content, false);

      try {
        // 修复：参考 Python chat() 函数，需要 taskId, stepId, text, sessionId
        const response = await apiRequest<ApiResponse<ChatResponse>>({
          endpoint: API_ENDPOINTS.CHAT,
          method: 'POST',
          body: {
            taskId: trainTaskId, // 添加 taskId
            stepId: currentStepId, // 添加 stepId
            text: content, // 用 text 而不是 content
            sessionId,
          },
        });

        console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

        const data = response?.data;

        if (data) {
          const nextRound = dialogueRoundRef.current + 1;
          setDialogueRound(prev => prev + 1);
          await appendLogEntry({
            type: 'chat',
            timestamp: Date.now(),
            stepId: currentStepId,
            stepName: getStepDisplayName(currentStepId),
            round: nextRound,
            source: 'chat',
            userText: content,
            aiText: data.text ?? undefined,
          });
        }

        // 检查返回结果，如果 text 为 null 且 nextStepId 为 null，代表输出结束
        if (data?.text == null && data?.nextStepId == null) {
          completeTraining();
        } else {
          if (data?.text) {
            addMessage('assistant', data.text);
          }

          // chat 返回 nextStepId 时，自动切换到下一步并运行 runCard
          if (data?.nextStepId) {
            if (isTerminalStep(data.nextStepId)) {
              setCurrentStepId(data.nextStepId);
              currentStepIdRef.current = data.nextStepId;
              completeTraining();
            } else {
              announceNextStep(data.nextStepId);
              await runCardForStep(data.nextStepId, sessionId);
            }
          }
        }
      } catch (err) {
        setError((err as Error).message);
        addMessage('system', `发送失败: ${(err as Error).message}`);
      } finally {
        setIsLoading(false);
      }
    },
    [
      sessionId,
      trainTaskId,
      currentStepId,
      workflowState,
      addMessage,
      runCardForStep,
      stopAutoRun,
      appendLogEntry,
      getStepDisplayName,
      announceNextStep,
      isTerminalStep,
      completeTraining,
    ],
  );

  // AI自动生成回答（使用LLM模型）
  const autoGenerate = useCallback(async (): Promise<{ needConfig: boolean }> => {
    const activeSessionId = sessionIdRef.current;
    const activeTrainTaskId = trainTaskIdRef.current;
    const activeStepId = currentStepIdRef.current;
    const activeWorkflowState = workflowStateRef.current;

    if (!activeSessionId || !activeTrainTaskId || !activeStepId || activeWorkflowState !== 'CHATTING') {
      return { needConfig: false };
    }

    const latestMessages = messagesRef.current;
    // 获取最后一条 AI 消息作为问题
    const lastAssistantMessage = [...latestMessages].reverse().find(m => m.role === 'assistant');
    if (!lastAssistantMessage) {
      addMessage('system', '没有找到 AI 的问题，请先等待 AI 提问');
      return { needConfig: false };
    }

    setIsLoading(true);
    let generatingMessageId: string | null = null;

    try {
      const llmConfig = await llmConfigStorage.get();
      const modelName = llmConfig.model || 'LLM';
      generatingMessageId = addMessage('system', `正在使用 ${modelName} 模型生成回答...`, false, activeStepId).id;

      // 构建对话历史
      const conversationHistory: Array<{ ai: string; student: string }> = [];
      for (let i = 0; i < latestMessages.length - 1; i++) {
        if (latestMessages[i].role === 'assistant' && latestMessages[i + 1]?.role === 'user') {
          conversationHistory.push({
            ai: latestMessages[i].content,
            student: latestMessages[i + 1].content,
          });
        }
      }

      // 调用 LLM 生成回答
      const llmResult = await generateStudentAnswer(lastAssistantMessage.content, conversationHistory);

      if (!llmResult.success) {
        if (llmResult.error?.includes('请先配置')) {
          addMessage('system', '⚠️ 请先配置 LLM API Key');
          return { needConfig: true };
        }
        addMessage('system', `❌ 生成失败: ${llmResult.error}`);
        return { needConfig: false };
      }

      const generatedAnswer = llmResult.content!;
      console.log('🤖 LLM 生成的回答:', generatedAnswer);

      // 显示生成的用户回答（携带生成模型，用于在气泡上标明品牌）
      addMessage('user', generatedAnswer, true, activeStepId, modelName);

      // 发送回答到服务器
      const response = await apiRequest<ApiResponse<ChatResponse>>({
        endpoint: API_ENDPOINTS.CHAT,
        method: 'POST',
        body: {
          taskId: activeTrainTaskId,
          stepId: activeStepId,
          text: generatedAnswer,
          sessionId: activeSessionId,
        },
      });

      console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

      const data = response?.data;

      if (data) {
        const nextRound = dialogueRoundRef.current + 1;
        setDialogueRound(prev => prev + 1);
        await appendLogEntry({
          type: 'chat',
          timestamp: Date.now(),
          stepId: activeStepId,
          stepName: getStepDisplayName(activeStepId),
          round: nextRound,
          source: 'chat',
          userText: generatedAnswer,
          aiText: data.text ?? undefined,
        });
      }

      // 检查返回结果，如果 text 为 null 且 nextStepId 为 null，代表输出结束
      if (data?.text == null && data?.nextStepId == null) {
        completeTraining();
      } else {
        if (data?.text) {
          addMessage('assistant', data.text, false, activeStepId);
        }

        // chat 返回 nextStepId 时，自动切换到下一步并运行 runCard
        if (data?.nextStepId) {
          if (isTerminalStep(data.nextStepId)) {
            setCurrentStepId(data.nextStepId);
            currentStepIdRef.current = data.nextStepId;
            completeTraining();
          } else {
            announceNextStep(data.nextStepId);
            await runCardForStep(data.nextStepId, activeSessionId);
          }
        }
      }

      return { needConfig: false };
    } catch (err) {
      setError((err as Error).message);
      addMessage('system', `❌ 自动生成失败: ${(err as Error).message}`);
      return { needConfig: false };
    } finally {
      if (generatingMessageId) {
        setMessages(prev => prev.filter(message => message.id !== generatingMessageId));
      }
      setIsLoading(false);
    }
  }, [
    addMessage,
    runCardForStep,
    appendLogEntry,
    getStepDisplayName,
    announceNextStep,
    isTerminalStep,
    completeTraining,
  ]);

  const startAutoRun = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (autoRunActiveRef.current) {
      return { needConfig: false };
    }

    if (!sessionId || !trainTaskId || !currentStepId) {
      return { needConfig: false };
    }

    autoRunActiveRef.current = true;
    autoRunTokenRef.current += 1;
    const token = autoRunTokenRef.current;
    setIsAutoRunning(true);

    let needConfig = false;

    const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

    while (autoRunActiveRef.current && token === autoRunTokenRef.current) {
      const state = workflowStateRef.current;
      if (state === 'COMPLETED' || state === 'ERROR' || state === 'IDLE') {
        break;
      }

      if (state !== 'CHATTING' || isLoadingRef.current) {
        await sleep(300);
        continue;
      }

      const result = await autoGenerate();
      if (result.needConfig) {
        needConfig = true;
        break;
      }

      await sleep(500);
    }

    if (token === autoRunTokenRef.current) {
      autoRunActiveRef.current = false;
    }
    setIsAutoRunning(false);

    return { needConfig };
  }, [autoGenerate, currentStepId, sessionId, trainTaskId]);

  // 重置对话
  const reset = useCallback(() => {
    abortControllerRef.current?.abort();
    stopAutoRun();
    setSessionId(null);
    setCurrentStepId(null);
    setWorkflowState('IDLE');
    setMessages([]);
    setDialogueRound(0);
    setError(null);
    setIsLoading(false);
    setActiveLogSessionId(null);
    activeLogSessionIdRef.current = null;
    stepNameMappingRef.current = {};
    stepNodeTypeByIdRef.current = {};
    dialogueRoundRef.current = 0;
    setScriptSteps([]);
    scriptStepsRef.current = [];
    setStepListError(null);
    setIsStepListLoading(false);
  }, [stopAutoRun]);

  return {
    // 状态
    trainTaskId,
    sessionId,
    workflowState,
    messages,
    isLoading,
    error,
    dialogueRound,
    isAutoRunning,
    scriptSteps,
    isStepListLoading,
    stepListError,

    // 操作
    startConversation,
    sendMessage,
    autoGenerate,
    startAutoRun,
    stopAutoRun,
    fetchScriptSteps,
    runDebugStep,
    reset,
    initialize,
  };
};

export { useAgentChat };
export type { WorkflowState, MessageRole, ChatMessage };
