/**
 * 智能体对话Hook
 * 管理对话状态和工作流
 */

import { useState, useCallback, useEffect, useRef } from 'react';
import {
  apiRequest,
  extractTrainTaskId,
  onTabUrlChanged,
  API_ENDPOINTS,
} from '../services/background-bridge';
import { generateStudentAnswer } from '../services/llm-service';

// ============ 类型定义 ============
export type WorkflowState =
  | 'IDLE'
  | 'FETCHING_STEPS'
  | 'FETCHING_FIRST_STEP'
  | 'RUNNING_CARD'
  | 'CHATTING'
  | 'COMPLETED'
  | 'ERROR';

export type MessageRole = 'user' | 'assistant' | 'system';

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
}

interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

// API 返回的步骤列表项结构（参考 Python: workflow_tester_base.py）
interface ScriptStepItem {
  stepId: string;  // 步骤ID（用于 runCard）
  stepDetailDTO?: {
    stepName?: string;
    stepOrder?: number;
  };
}

// 用于 queryScriptStepFlowList 的结构
interface ScriptStepFlow {
  scriptStepEndId: string;  // 第一个真实步骤的ID
}

interface RunCardResponse {
  sessionId: string;
  text?: string;  // Python 代码中用的是 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
}

interface ChatResponse {
  text?: string;  // 修复：用 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
  isCompleted?: boolean;
}

// ============ Hook实现 ============
export function useAgentChat() {
  // 状态
  const [trainTaskId, setTrainTaskId] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [currentStepId, setCurrentStepId] = useState<string | null>(null);
  const [workflowState, setWorkflowState] = useState<WorkflowState>('IDLE');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dialogueRound, setDialogueRound] = useState(0);

  // 用于取消请求
  const abortControllerRef = useRef<AbortController | null>(null);

  // 生成消息ID
  const generateMessageId = useCallback(() => {
    return `msg_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
  }, []);

  // 添加消息
  const addMessage = useCallback(
    (role: MessageRole, content: string, isAutoGenerated = false) => {
      const message: ChatMessage = {
        id: generateMessageId(),
        role,
        content,
        timestamp: Date.now(),
        stepId: currentStepId ?? undefined,
        isAutoGenerated,
      };
      setMessages(prev => [...prev, message]);
      return message;
    },
    [generateMessageId, currentStepId],
  );

  // 初始化 - 从URL提取trainTaskId
  const initialize = useCallback(async () => {
    const taskId = await extractTrainTaskId();
    if (taskId) {
      setTrainTaskId(taskId);
      addMessage('system', `已检测到训练任务: ${taskId.substring(0, 8)}...`);
    }
  }, [addMessage]);

  // 监听URL变化
  useEffect(() => {
    initialize();

    const unsubscribe = onTabUrlChanged(async (url) => {
      if (url.includes('trainTaskId=')) {
        const taskId = await extractTrainTaskId(url);
        if (taskId && taskId !== trainTaskId) {
          setTrainTaskId(taskId);
          // 重置状态
          setSessionId(null);
          setCurrentStepId(null);
          setWorkflowState('IDLE');
          setMessages([]);
          setDialogueRound(0);
          addMessage('system', `已切换到新任务: ${taskId.substring(0, 8)}...`);
        }
      }
    });

    return unsubscribe;
  }, [initialize, trainTaskId, addMessage]);

  // 开始对话流程
  const startConversation = useCallback(async () => {
    if (!trainTaskId) {
      setError('未找到训练任务ID，请确保在正确的页面打开');
      return;
    }

    setError(null);
    setIsLoading(true);

    try {
      // 步骤1: 获取步骤列表
      setWorkflowState('FETCHING_STEPS');
      addMessage('system', '正在获取训练步骤...');

      const stepsResponse = await apiRequest<ApiResponse<ScriptStepItem[]>>({
        endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_LIST,
        method: 'POST',
        body: { trainTaskId, trainSubType: 'ability' },  // 添加 trainSubType 参数
      });

      console.log('🔍 Steps Response:', JSON.stringify(stepsResponse, null, 2));

      if (!stepsResponse?.data?.length) {
        throw new Error('获取步骤列表失败');
      }

      const steps = stepsResponse.data;
      console.log('📋 First Step:', JSON.stringify(steps[0], null, 2));

      // 优先通过 flowList 获取第一个真实步骤（参考 Python: _query_first_step_from_flow）
      let firstStepId: string | null = null;
      let firstStepName = '未知步骤';

      try {
        const flowResponse = await apiRequest<ApiResponse<ScriptStepFlow[]>>({
          endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_FLOW_LIST,
          method: 'POST',
          body: { trainTaskId },
        });
        console.log('🔗 Flow Response:', JSON.stringify(flowResponse, null, 2));

        if (flowResponse?.data?.length) {
          firstStepId = flowResponse.data[0].scriptStepEndId;
        }
      } catch (e) {
        console.warn('⚠️ flowList 获取失败，使用回退逻辑');
      }

      // 回退逻辑：如果 flowList 失败，使用 stepOrder 排序（参考 Python 第 557-559 行）
      if (!firstStepId) {
        // Python 代码: first_idx = 2 if len(data) > 2 else 0
        const firstIdx = steps.length > 2 ? 2 : 0;
        firstStepId = steps[firstIdx].stepId;
      }

      // 获取步骤名称
      const matchedStep = steps.find(s => s.stepId === firstStepId);
      if (matchedStep?.stepDetailDTO?.stepName) {
        firstStepName = matchedStep.stepDetailDTO.stepName;
      }

      setCurrentStepId(firstStepId);

      // 步骤2: 启动卡片
      setWorkflowState('RUNNING_CARD');
      addMessage('system', `正在启动步骤: ${firstStepName}...`);

      // 关键修复：使用 taskId 而不是 trainTaskId（参考 Python: run_card 第 575 行）
      const runCardResponse = await apiRequest<ApiResponse<RunCardResponse>>({
        endpoint: API_ENDPOINTS.RUN_CARD,
        method: 'POST',
        body: { taskId: trainTaskId, stepId: firstStepId },  // ← 修复：taskId
      });

      console.log('🎴 RunCard Response:', JSON.stringify(runCardResponse, null, 2));

      if (!runCardResponse?.data?.sessionId) {
        console.error('❌ sessionId 未找到，完整响应:', runCardResponse);
        throw new Error('启动对话失败');
      }

      setSessionId(runCardResponse.data.sessionId);
      setWorkflowState('CHATTING');
      setDialogueRound(1);

      // 显示AI的初始消息（Python 代码用的是 text 字段）
      if (runCardResponse.data.text) {
        addMessage('assistant', runCardResponse.data.text);
      }

      addMessage('system', '对话已开始，请输入你的回答或点击AI自动回答');
    } catch (err) {
      setWorkflowState('ERROR');
      setError((err as Error).message);
      addMessage('system', `错误: ${(err as Error).message}`);
    } finally {
      setIsLoading(false);
    }
  }, [trainTaskId, addMessage]);

  // 发送用户消息
  const sendMessage = useCallback(
    async (content: string) => {
      if (!sessionId || !trainTaskId || !currentStepId || workflowState !== 'CHATTING') {
        return;
      }

      setIsLoading(true);
      addMessage('user', content, false);

      try {
        // 修复：参考 Python chat() 函数，需要 taskId, stepId, text, sessionId
        const response = await apiRequest<ApiResponse<ChatResponse>>({
          endpoint: API_ENDPOINTS.CHAT,
          method: 'POST',
          body: {
            taskId: trainTaskId,      // 添加 taskId
            stepId: currentStepId,    // 添加 stepId
            text: content,            // 用 text 而不是 content
            sessionId,
          },
        });

        console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

        if (response?.data?.text) {
          addMessage('assistant', response.data.text);
          setDialogueRound(prev => prev + 1);
        }

        // 处理步骤跳转（参考 Python 第 656-660 行）
        if (response?.data?.needSkipStep && response?.data?.nextStepId) {
          setCurrentStepId(response.data.nextStepId);
          // TODO: 可能需要调用 runCard 获取下一步的 AI 消息
        }

        if (response?.data?.isCompleted) {
          setWorkflowState('COMPLETED');
          addMessage('system', '恭喜！训练已完成！');
        }
      } catch (err) {
        setError((err as Error).message);
        addMessage('system', `发送失败: ${(err as Error).message}`);
      } finally {
        setIsLoading(false);
      }
    },
    [sessionId, trainTaskId, currentStepId, workflowState, addMessage],
  );

  // AI自动生成回答（使用豆包模型）
  const autoGenerate = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (!sessionId || !trainTaskId || !currentStepId || workflowState !== 'CHATTING') {
      return { needConfig: false };
    }

    // 获取最后一条 AI 消息作为问题
    const lastAssistantMessage = [...messages].reverse().find(m => m.role === 'assistant');
    if (!lastAssistantMessage) {
      addMessage('system', '没有找到 AI 的问题，请先等待 AI 提问');
      return { needConfig: false };
    }

    setIsLoading(true);
    addMessage('system', '🤖 正在使用豆包模型生成回答...');

    try {
      // 构建对话历史
      const conversationHistory: Array<{ ai: string; student: string }> = [];
      for (let i = 0; i < messages.length - 1; i++) {
        if (messages[i].role === 'assistant' && messages[i + 1]?.role === 'user') {
          conversationHistory.push({
            ai: messages[i].content,
            student: messages[i + 1].content,
          });
        }
      }

      // 调用 LLM 生成回答
      const llmResult = await generateStudentAnswer(lastAssistantMessage.content, conversationHistory);

      // 移除"正在生成"的消息
      setMessages(prev => prev.filter(m => !m.content.includes('正在使用豆包模型')));

      if (!llmResult.success) {
        if (llmResult.error?.includes('请先配置')) {
          addMessage('system', '⚠️ 请先配置 LLM API Key');
          return { needConfig: true };
        }
        addMessage('system', `❌ 生成失败: ${llmResult.error}`);
        return { needConfig: false };
      }

      const generatedAnswer = llmResult.content!;
      console.log('🤖 LLM 生成的回答:', generatedAnswer);

      // 显示生成的用户回答
      addMessage('user', generatedAnswer, true);

      // 发送回答到服务器
      const response = await apiRequest<ApiResponse<ChatResponse>>({
        endpoint: API_ENDPOINTS.CHAT,
        method: 'POST',
        body: {
          taskId: trainTaskId,
          stepId: currentStepId,
          text: generatedAnswer,
          sessionId,
        },
      });

      console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

      if (response?.data?.text) {
        addMessage('assistant', response.data.text);
        setDialogueRound(prev => prev + 1);
      }

      // 处理步骤跳转
      if (response?.data?.needSkipStep && response?.data?.nextStepId) {
        setCurrentStepId(response.data.nextStepId);
      }

      if (response?.data?.isCompleted) {
        setWorkflowState('COMPLETED');
        addMessage('system', '🎉 恭喜！训练已完成！');
      }

      return { needConfig: false };
    } catch (err) {
      setError((err as Error).message);
      addMessage('system', `❌ 自动生成失败: ${(err as Error).message}`);
      return { needConfig: false };
    } finally {
      setIsLoading(false);
    }
  }, [sessionId, trainTaskId, currentStepId, workflowState, messages, addMessage]);

  // 重置对话
  const reset = useCallback(() => {
    abortControllerRef.current?.abort();
    setSessionId(null);
    setCurrentStepId(null);
    setWorkflowState('IDLE');
    setMessages([]);
    setDialogueRound(0);
    setError(null);
    setIsLoading(false);
  }, []);

  return {
    // 状态
    trainTaskId,
    sessionId,
    workflowState,
    messages,
    isLoading,
    error,
    dialogueRound,

    // 操作
    startConversation,
    sendMessage,
    autoGenerate,
    reset,
    initialize,
  };
}
