/**
 * 智能体对话Hook
 * 管理对话状态和工作流
 */

import { apiRequest, extractTrainTaskId, onTabUrlChanged, API_ENDPOINTS } from '../services/background-bridge';
import { generateStudentAnswer } from '../services/llm-service';
import { agentLogStorage } from '@extension/storage';
import { useState, useCallback, useEffect, useRef } from 'react';
import type { AgentLogEntry } from '@extension/storage';

// ============ 类型定义 ============
type WorkflowState =
  | 'IDLE'
  | 'FETCHING_STEPS'
  | 'FETCHING_FIRST_STEP'
  | 'RUNNING_CARD'
  | 'CHATTING'
  | 'COMPLETED'
  | 'ERROR';

type MessageRole = 'user' | 'assistant' | 'system';

interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
}

interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

// API 返回的步骤列表项结构（参考 Python: workflow_tester_base.py）
interface ScriptStepItem {
  stepId: string; // 步骤ID（用于 runCard）
  stepDetailDTO?: {
    stepName?: string;
    stepOrder?: number;
  };
}

// 用于 queryScriptStepFlowList 的结构
interface ScriptStepFlow {
  scriptStepEndId: string; // 第一个真实步骤的ID
}

interface TrainConfigurationResponse {
  trainTaskName?: string;
}

interface RunCardResponse {
  sessionId: string;
  text?: string; // Python 代码中用的是 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
}

interface ChatResponse {
  text?: string; // Python 代码中用的是 text 而不是 content
  needSkipStep?: boolean;
  nextStepId?: string;
  // 结束判断：当 text 和 nextStepId 都为 null 时表示完成
}

// ============ Hook实现 ============
const useAgentChat = () => {
  // 状态
  const [trainTaskId, setTrainTaskId] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [currentStepId, setCurrentStepId] = useState<string | null>(null);
  const [workflowState, setWorkflowState] = useState<WorkflowState>('IDLE');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dialogueRound, setDialogueRound] = useState(0);
  const [isAutoRunning, setIsAutoRunning] = useState(false);
  const [activeLogSessionId, setActiveLogSessionId] = useState<string | null>(null);

  // 用于取消请求
  const abortControllerRef = useRef<AbortController | null>(null);
  const autoRunActiveRef = useRef(false);
  const autoRunTokenRef = useRef(0);
  const messagesRef = useRef<ChatMessage[]>([]);
  const workflowStateRef = useRef<WorkflowState>('IDLE');
  const isLoadingRef = useRef(false);
  const sessionIdRef = useRef<string | null>(null);
  const currentStepIdRef = useRef<string | null>(null);
  const trainTaskIdRef = useRef<string | null>(null);
  const dialogueRoundRef = useRef(0);
  const activeLogSessionIdRef = useRef<string | null>(null);
  const stepNameMappingRef = useRef<Record<string, string>>({});

  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  useEffect(() => {
    workflowStateRef.current = workflowState;
  }, [workflowState]);

  useEffect(() => {
    isLoadingRef.current = isLoading;
  }, [isLoading]);

  useEffect(() => {
    sessionIdRef.current = sessionId;
  }, [sessionId]);

  useEffect(() => {
    currentStepIdRef.current = currentStepId;
  }, [currentStepId]);

  useEffect(() => {
    trainTaskIdRef.current = trainTaskId;
  }, [trainTaskId]);

  useEffect(() => {
    dialogueRoundRef.current = dialogueRound;
  }, [dialogueRound]);

  useEffect(() => {
    activeLogSessionIdRef.current = activeLogSessionId;
  }, [activeLogSessionId]);

  const fetchTrainTaskName = useCallback(async (taskId: string): Promise<string | undefined> => {
    const configResponse = await apiRequest<ApiResponse<TrainConfigurationResponse>>({
      endpoint: API_ENDPOINTS.QUERY_CONFIGURATION,
      method: 'POST',
      body: { trainTaskId: taskId },
    });
    return configResponse?.data?.trainTaskName;
  }, []);

  const getStepDisplayName = useCallback((stepId: string) => stepNameMappingRef.current[stepId] ?? stepId, []);

  const appendLogEntry = useCallback(async (entry: AgentLogEntry) => {
    const sessionId = activeLogSessionIdRef.current;
    if (!sessionId) {
      return;
    }
    await agentLogStorage.addEntry(sessionId, entry);
  }, []);

  // 生成消息ID
  const generateMessageId = useCallback(() => `msg_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`, []);

  // 添加消息
  const addMessage = useCallback(
    (role: MessageRole, content: string, isAutoGenerated = false, stepIdOverride?: string) => {
      const message: ChatMessage = {
        id: generateMessageId(),
        role,
        content,
        timestamp: Date.now(),
        stepId: stepIdOverride ?? currentStepId ?? undefined,
        isAutoGenerated,
      };
      setMessages(prev => [...prev, message]);
      return message;
    },
    [generateMessageId, currentStepId],
  );

  const announceNextStep = useCallback(
    (stepId: string) => {
      const stepName = getStepDisplayName(stepId);
      addMessage('system', `进入下一个阶段——${stepName}`, false, stepId);
    },
    [addMessage, getStepDisplayName],
  );

  const runCardForStep = useCallback(
    async (stepId: string, sessionOverride?: string | null) => {
      if (!trainTaskId) {
        throw new Error('未找到训练任务ID');
      }

      setWorkflowState('RUNNING_CARD');

      const runCardResponse = await apiRequest<ApiResponse<RunCardResponse>>({
        endpoint: API_ENDPOINTS.RUN_CARD,
        method: 'POST',
        body: {
          taskId: trainTaskId,
          stepId,
          sessionId: sessionOverride ?? sessionId ?? undefined,
        },
      });

      console.log('🎴 RunCard Response:', JSON.stringify(runCardResponse, null, 2));

      if (!runCardResponse?.data?.sessionId) {
        console.error('❌ sessionId 未找到，完整响应:', runCardResponse);
        throw new Error('启动对话失败');
      }

      setSessionId(runCardResponse.data.sessionId);
      sessionIdRef.current = runCardResponse.data.sessionId;
      setCurrentStepId(stepId);
      currentStepIdRef.current = stepId;
      setWorkflowState('CHATTING');

      if (runCardResponse.data.text) {
        addMessage('assistant', runCardResponse.data.text, false, stepId);
        await appendLogEntry({
          type: 'chat',
          timestamp: Date.now(),
          stepId,
          stepName: getStepDisplayName(stepId),
          round: dialogueRoundRef.current,
          source: 'runCard',
          aiText: runCardResponse.data.text,
        });
      }

      if (runCardResponse.data.needSkipStep && runCardResponse.data.nextStepId) {
        const nextStepId = runCardResponse.data.nextStepId;
        setCurrentStepId(nextStepId);
        currentStepIdRef.current = nextStepId;
        announceNextStep(nextStepId);
        return runCardForStep(nextStepId, runCardResponse.data.sessionId);
      }

      return runCardResponse;
    },
    [trainTaskId, sessionId, addMessage, appendLogEntry, getStepDisplayName, announceNextStep],
  );

  // 初始化 - 从URL提取trainTaskId
  const initialize = useCallback(async () => {
    const taskId = await extractTrainTaskId();
    if (taskId) {
      const taskName = await fetchTrainTaskName(taskId);
      setTrainTaskId(taskId);
      const displayName = taskName?.trim() || `${taskId.substring(0, 8)}...`;
      addMessage('system', `已检测到训练任务: ${displayName}`);
    }
  }, [addMessage, fetchTrainTaskName]);

  // 监听URL变化
  useEffect(() => {
    initialize();

    const unsubscribe = onTabUrlChanged(async url => {
      if (url.includes('trainTaskId=')) {
        const taskId = await extractTrainTaskId(url);
        if (taskId && taskId !== trainTaskId) {
          const taskName = await fetchTrainTaskName(taskId);
          setTrainTaskId(taskId);
          // 重置状态
          setSessionId(null);
          setCurrentStepId(null);
          setWorkflowState('IDLE');
          setMessages([]);
          setDialogueRound(0);
          setActiveLogSessionId(null);
          activeLogSessionIdRef.current = null;
          stepNameMappingRef.current = {};
          const displayName = taskName?.trim() || `${taskId.substring(0, 8)}...`;
          addMessage('system', `已切换到新任务: ${displayName}`);
        }
      }
    });

    return unsubscribe;
  }, [initialize, trainTaskId, addMessage, fetchTrainTaskName]);

  // 开始对话流程
  const startConversation = useCallback(async () => {
    if (!trainTaskId) {
      setError('未找到训练任务ID，请确保在正确的页面打开');
      return;
    }

    setError(null);
    setIsLoading(true);

    try {
      // 步骤1: 获取任务配置（用于日志命名）
      const taskName = await fetchTrainTaskName(trainTaskId);

      // 步骤2: 获取步骤列表
      setWorkflowState('FETCHING_STEPS');
      addMessage('system', '正在获取训练步骤...');

      const stepsResponse = await apiRequest<ApiResponse<ScriptStepItem[]>>({
        endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_LIST,
        method: 'POST',
        body: { trainTaskId, trainSubType: 'ability' }, // 添加 trainSubType 参数
      });

      console.log('🔍 Steps Response:', JSON.stringify(stepsResponse, null, 2));

      if (!stepsResponse?.data?.length) {
        throw new Error('获取步骤列表失败');
      }

      const steps = stepsResponse.data;
      console.log('📋 First Step:', JSON.stringify(steps[0], null, 2));

      const stepNameMapping: Record<string, string> = {};
      steps.forEach(step => {
        if (step.stepDetailDTO?.stepName) {
          stepNameMapping[step.stepId] = step.stepDetailDTO.stepName;
        }
      });
      stepNameMappingRef.current = stepNameMapping;

      try {
        const newSession = await agentLogStorage.createSession({ taskId: trainTaskId, taskName, stepNameMapping });
        setActiveLogSessionId(newSession.id);
        activeLogSessionIdRef.current = newSession.id;
      } catch (logError) {
        console.warn('⚠️ 日志初始化失败:', logError);
      }

      // 优先通过 flowList 获取第一个真实步骤（参考 Python: _query_first_step_from_flow）
      let firstStepId: string | null = null;
      let firstStepName = '未知步骤';

      try {
        const flowResponse = await apiRequest<ApiResponse<ScriptStepFlow[]>>({
          endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_FLOW_LIST,
          method: 'POST',
          body: { trainTaskId },
        });
        console.log('🔗 Flow Response:', JSON.stringify(flowResponse, null, 2));

        if (flowResponse?.data?.length) {
          firstStepId = flowResponse.data[0].scriptStepEndId;
        }
      } catch {
        console.warn('⚠️ flowList 获取失败，使用回退逻辑');
      }

      // 回退逻辑：如果 flowList 失败，使用 stepOrder 排序（参考 Python 第 557-559 行）
      if (!firstStepId) {
        // Python 代码: first_idx = 2 if len(data) > 2 else 0
        const firstIdx = steps.length > 2 ? 2 : 0;
        firstStepId = steps[firstIdx].stepId;
      }

      const matchedStep = steps.find(s => s.stepId === firstStepId);
      if (matchedStep?.stepDetailDTO?.stepName) {
        firstStepName = matchedStep.stepDetailDTO.stepName;
      }

      setCurrentStepId(firstStepId);
      currentStepIdRef.current = firstStepId;

      // 步骤2: 启动卡片
      addMessage('system', `正在启动步骤: ${firstStepName}...`);

      await runCardForStep(firstStepId);
      setDialogueRound(1);

      addMessage('system', '对话已开始，请输入你的回答或点击AI自动回答');
    } catch (err) {
      setWorkflowState('ERROR');
      setError((err as Error).message);
      addMessage('system', `错误: ${(err as Error).message}`);
    } finally {
      setIsLoading(false);
    }
  }, [trainTaskId, addMessage, runCardForStep, fetchTrainTaskName]);

  const stopAutoRun = useCallback(() => {
    if (!autoRunActiveRef.current) {
      return;
    }
    autoRunActiveRef.current = false;
    autoRunTokenRef.current += 1;
    setIsAutoRunning(false);
  }, []);

  // 发送用户消息
  const sendMessage = useCallback(
    async (content: string) => {
      if (!sessionId || !trainTaskId || !currentStepId || workflowState !== 'CHATTING') {
        return;
      }

      stopAutoRun();
      setIsLoading(true);
      addMessage('user', content, false);

      try {
        // 修复：参考 Python chat() 函数，需要 taskId, stepId, text, sessionId
        const response = await apiRequest<ApiResponse<ChatResponse>>({
          endpoint: API_ENDPOINTS.CHAT,
          method: 'POST',
          body: {
            taskId: trainTaskId, // 添加 taskId
            stepId: currentStepId, // 添加 stepId
            text: content, // 用 text 而不是 content
            sessionId,
          },
        });

        console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

        const data = response?.data;

        if (data) {
          const nextRound = dialogueRoundRef.current + 1;
          setDialogueRound(prev => prev + 1);
          await appendLogEntry({
            type: 'chat',
            timestamp: Date.now(),
            stepId: currentStepId,
            stepName: getStepDisplayName(currentStepId),
            round: nextRound,
            source: 'chat',
            userText: content,
            aiText: data.text ?? undefined,
          });
        }

        // 检查返回结果，如果 text 为 null 且 nextStepId 为 null，代表输出结束
        if (data?.text == null && data?.nextStepId == null) {
          setWorkflowState('COMPLETED');
          addMessage('system', '✅ 恭喜！训练已完成！');
        } else {
          if (data?.text) {
            addMessage('assistant', data.text);
          }

          // chat 返回 nextStepId 时，自动切换到下一步并运行 runCard
          if (data?.nextStepId) {
            announceNextStep(data.nextStepId);
            await runCardForStep(data.nextStepId, sessionId);
          }
        }
      } catch (err) {
        setError((err as Error).message);
        addMessage('system', `发送失败: ${(err as Error).message}`);
      } finally {
        setIsLoading(false);
      }
    },
    [
      sessionId,
      trainTaskId,
      currentStepId,
      workflowState,
      addMessage,
      runCardForStep,
      stopAutoRun,
      appendLogEntry,
      getStepDisplayName,
      announceNextStep,
    ],
  );

  // AI自动生成回答（使用豆包模型）
  const autoGenerate = useCallback(async (): Promise<{ needConfig: boolean }> => {
    const activeSessionId = sessionIdRef.current;
    const activeTrainTaskId = trainTaskIdRef.current;
    const activeStepId = currentStepIdRef.current;
    const activeWorkflowState = workflowStateRef.current;

    if (!activeSessionId || !activeTrainTaskId || !activeStepId || activeWorkflowState !== 'CHATTING') {
      return { needConfig: false };
    }

    const latestMessages = messagesRef.current;
    // 获取最后一条 AI 消息作为问题
    const lastAssistantMessage = [...latestMessages].reverse().find(m => m.role === 'assistant');
    if (!lastAssistantMessage) {
      addMessage('system', '没有找到 AI 的问题，请先等待 AI 提问');
      return { needConfig: false };
    }

    setIsLoading(true);
    addMessage('system', '🤖 正在使用豆包模型生成回答...');

    try {
      // 构建对话历史
      const conversationHistory: Array<{ ai: string; student: string }> = [];
      for (let i = 0; i < latestMessages.length - 1; i++) {
        if (latestMessages[i].role === 'assistant' && latestMessages[i + 1]?.role === 'user') {
          conversationHistory.push({
            ai: latestMessages[i].content,
            student: latestMessages[i + 1].content,
          });
        }
      }

      // 调用 LLM 生成回答
      const llmResult = await generateStudentAnswer(lastAssistantMessage.content, conversationHistory);

      // 移除"正在生成"的消息
      setMessages(prev => prev.filter(m => !m.content.includes('正在使用豆包模型')));

      if (!llmResult.success) {
        if (llmResult.error?.includes('请先配置')) {
          addMessage('system', '⚠️ 请先配置 LLM API Key');
          return { needConfig: true };
        }
        addMessage('system', `❌ 生成失败: ${llmResult.error}`);
        return { needConfig: false };
      }

      const generatedAnswer = llmResult.content!;
      console.log('🤖 LLM 生成的回答:', generatedAnswer);

      // 显示生成的用户回答
      addMessage('user', generatedAnswer, true, activeStepId);

      // 发送回答到服务器
      const response = await apiRequest<ApiResponse<ChatResponse>>({
        endpoint: API_ENDPOINTS.CHAT,
        method: 'POST',
        body: {
          taskId: activeTrainTaskId,
          stepId: activeStepId,
          text: generatedAnswer,
          sessionId: activeSessionId,
        },
      });

      console.log('💬 Chat Response:', JSON.stringify(response, null, 2));

      const data = response?.data;

      if (data) {
        const nextRound = dialogueRoundRef.current + 1;
        setDialogueRound(prev => prev + 1);
        await appendLogEntry({
          type: 'chat',
          timestamp: Date.now(),
          stepId: activeStepId,
          stepName: getStepDisplayName(activeStepId),
          round: nextRound,
          source: 'chat',
          userText: generatedAnswer,
          aiText: data.text ?? undefined,
        });
      }

      // 检查返回结果，如果 text 为 null 且 nextStepId 为 null，代表输出结束
      if (data?.text == null && data?.nextStepId == null) {
        setWorkflowState('COMPLETED');
        addMessage('system', '✅ 恭喜！训练已完成！');
      } else {
        if (data?.text) {
          addMessage('assistant', data.text, false, activeStepId);
        }

        // chat 返回 nextStepId 时，自动切换到下一步并运行 runCard
        if (data?.nextStepId) {
          announceNextStep(data.nextStepId);
          await runCardForStep(data.nextStepId, activeSessionId);
        }
      }

      return { needConfig: false };
    } catch (err) {
      setError((err as Error).message);
      addMessage('system', `❌ 自动生成失败: ${(err as Error).message}`);
      return { needConfig: false };
    } finally {
      setIsLoading(false);
    }
  }, [addMessage, runCardForStep, appendLogEntry, getStepDisplayName, announceNextStep]);

  const startAutoRun = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (autoRunActiveRef.current) {
      return { needConfig: false };
    }

    if (!sessionId || !trainTaskId || !currentStepId) {
      return { needConfig: false };
    }

    autoRunActiveRef.current = true;
    autoRunTokenRef.current += 1;
    const token = autoRunTokenRef.current;
    setIsAutoRunning(true);

    let needConfig = false;

    const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

    while (autoRunActiveRef.current && token === autoRunTokenRef.current) {
      const state = workflowStateRef.current;
      if (state === 'COMPLETED' || state === 'ERROR' || state === 'IDLE') {
        break;
      }

      if (state !== 'CHATTING' || isLoadingRef.current) {
        await sleep(300);
        continue;
      }

      const result = await autoGenerate();
      if (result.needConfig) {
        needConfig = true;
        break;
      }

      await sleep(500);
    }

    if (token === autoRunTokenRef.current) {
      autoRunActiveRef.current = false;
    }
    setIsAutoRunning(false);

    return { needConfig };
  }, [autoGenerate, currentStepId, sessionId, trainTaskId]);

  // 重置对话
  const reset = useCallback(() => {
    abortControllerRef.current?.abort();
    stopAutoRun();
    setSessionId(null);
    setCurrentStepId(null);
    setWorkflowState('IDLE');
    setMessages([]);
    setDialogueRound(0);
    setError(null);
    setIsLoading(false);
    setActiveLogSessionId(null);
    activeLogSessionIdRef.current = null;
    stepNameMappingRef.current = {};
    dialogueRoundRef.current = 0;
  }, [stopAutoRun]);

  return {
    // 状态
    trainTaskId,
    sessionId,
    workflowState,
    messages,
    isLoading,
    error,
    dialogueRound,
    isAutoRunning,

    // 操作
    startConversation,
    sendMessage,
    autoGenerate,
    startAutoRun,
    stopAutoRun,
    reset,
    initialize,
  };
};

export { useAgentChat };
export type { WorkflowState, MessageRole, ChatMessage };
