/**
 * 多角色并行运行调度 Hook
 * 不侵入 useAgentChat.ts，独立管理多人运行生命周期
 */

import { apiRequest, API_ENDPOINTS } from '../services/background-bridge';
import { generateStudentAnswer } from '../services/llm-service';
import { MULTI_ROLE_POLL_INTERVAL_MS, MULTI_ROLE_RETRY_DELAY_MS } from '../types/multi-role-types';
import { agentLogStorage, llmConfigStorage } from '@extension/storage';
import { useState, useCallback, useRef, useEffect } from 'react';
import type { ChatMessage, WorkflowState } from './useAgentChat';
import type { RoleRunDraft, RoleRunState, MultiRoleRunBatch } from '../types/multi-role-types';
import type { AgentLogEntry, StudentProfile } from '@extension/storage';

// ============ API 类型（复用 useAgentChat 中同构的定义） ============

interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

type ScriptNodeType = 'SCRIPT_START' | 'SCRIPT_END' | 'SCRIPT_NODE';

interface ScriptStepItem {
  stepId: string;
  stepDetailDTO?: {
    stepName?: string;
    stepOrder?: number;
    nodeType?: ScriptNodeType;
  };
}

interface ScriptStepFlow {
  scriptStepStartId: string;
  scriptStepEndId: string;
  isDefault?: number;
}

interface TrainConfigurationResponse {
  trainTaskName?: string;
}

interface RunCardResponse {
  sessionId: string;
  text?: string;
  needSkipStep?: boolean;
  nextStepId?: string;
}

interface ChatResponse {
  text?: string;
  needSkipStep?: boolean;
  nextStepId?: string;
}

// ============ 工具函数 ============

const generateId = () => `${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;

const generateMessageId = () => `msg_${generateId()}`;

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const RETRYABLE_REQUEST_ERROR_PATTERNS = [/HTTP error:\s*(429|5\d\d)/i, /network/i, /failed to fetch/i, /timeout/i];

const shouldRetryRequestError = (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error ?? '');
  return RETRYABLE_REQUEST_ERROR_PATTERNS.some(pattern => pattern.test(message));
};

const isRoleTerminalState = (state: WorkflowState) => state === 'COMPLETED' || state === 'ERROR';

const createRoleRunState = (draft: RoleRunDraft, profile: StudentProfile): RoleRunState => ({
  profileId: draft.profileId,
  profileLabel: draft.profileLabel,
  profile,
  sessionId: null,
  currentStepId: null,
  messages: [],
  workflowState: 'IDLE' as WorkflowState,
  dialogueRound: 0,
  logSessionId: null,
  error: null,
});

const addRoleMessage = (
  role: RoleRunState,
  msgRole: ChatMessage['role'],
  content: string,
  isAutoGenerated = false,
  stepIdOverride?: string,
): RoleRunState => ({
  ...role,
  messages: [
    ...role.messages,
    {
      id: generateMessageId(),
      role: msgRole,
      content,
      timestamp: Date.now(),
      stepId: stepIdOverride ?? role.currentStepId ?? undefined,
      isAutoGenerated,
    },
  ],
});

/**
 * 从 flowList 解析默认路径上所有 SCRIPT_NODE 的 stepId（有序）
 * 复用 useAgentChat.ts:471-505 的首步定位策略
 */
const resolveOrderedNodeStepIds = (steps: ScriptStepItem[], flows: ScriptStepFlow[]): string[] => {
  const stepMap = new Map(steps.map(step => [step.stepId, step]));
  const orderedIds: string[] = [];
  const visited = new Set<string>();

  const startStep =
    steps.slice(0, 2).find(s => s.stepDetailDTO?.nodeType === 'SCRIPT_START') ??
    steps.find(s => s.stepDetailDTO?.nodeType === 'SCRIPT_START');

  if (!startStep) {
    return steps
      .filter(s => s.stepDetailDTO?.nodeType === 'SCRIPT_NODE')
      .sort(
        (a, b) =>
          (a.stepDetailDTO?.stepOrder ?? Number.MAX_SAFE_INTEGER) -
          (b.stepDetailDTO?.stepOrder ?? Number.MAX_SAFE_INTEGER),
      )
      .map(s => s.stepId);
  }

  let currentId: string | null = startStep.stepId;
  const visitedFlowStarts = new Set<string>();

  while (currentId && !visitedFlowStarts.has(currentId)) {
    visitedFlowStarts.add(currentId);
    const outgoing = flows.filter(f => f.scriptStepStartId === currentId);
    if (!outgoing.length) break;

    const selected = outgoing.find(f => f.isDefault === 1) ?? outgoing[0];
    currentId = selected?.scriptStepEndId ?? null;

    if (!currentId || visited.has(currentId)) break;

    const step = stepMap.get(currentId);
    if (!step || step.stepDetailDTO?.nodeType === 'SCRIPT_END') break;

    if (step.stepDetailDTO?.nodeType === 'SCRIPT_NODE') {
      visited.add(currentId);
      orderedIds.push(currentId);
    }
  }

  return orderedIds.length > 0
    ? orderedIds
    : steps
        .filter(s => s.stepDetailDTO?.nodeType === 'SCRIPT_NODE')
        .sort(
          (a, b) =>
            (a.stepDetailDTO?.stepOrder ?? Number.MAX_SAFE_INTEGER) -
            (b.stepDetailDTO?.stepOrder ?? Number.MAX_SAFE_INTEGER),
        )
        .map(s => s.stepId);
};

/**
 * 从 steps + flows 确定首个真实步骤 ID
 * 复用 useAgentChat.ts:471-505 的逻辑
 */
const resolveFirstStepId = (steps: ScriptStepItem[], flows: ScriptStepFlow[]): string | null => {
  const startStep =
    steps.slice(0, 2).find(s => s.stepDetailDTO?.nodeType === 'SCRIPT_START') ??
    steps.find(s => s.stepDetailDTO?.nodeType === 'SCRIPT_START');

  if (startStep && flows.length > 0) {
    const matched =
      flows.find(f => f.scriptStepStartId === startStep.stepId && f.isDefault === 1) ??
      flows.find(f => f.scriptStepStartId === startStep.stepId);
    if (matched?.scriptStepEndId) return matched.scriptStepEndId;
  }

  const fallback =
    steps.find(s => {
      const nodeType = s.stepDetailDTO?.nodeType;
      return nodeType && nodeType !== 'SCRIPT_START' && nodeType !== 'SCRIPT_END';
    }) ?? steps[steps.length > 2 ? 2 : 0];

  return fallback?.stepId ?? null;
};

const buildStepNameMapping = (steps: ScriptStepItem[]): Record<string, string> => {
  const mapping: Record<string, string> = {};
  for (const step of steps) {
    if (step.stepDetailDTO?.stepName) {
      mapping[step.stepId] = step.stepDetailDTO.stepName;
    }
  }
  return mapping;
};

const buildStepNodeTypeMapping = (steps: ScriptStepItem[]): Record<string, ScriptNodeType> => {
  const mapping: Record<string, ScriptNodeType> = {};
  for (const step of steps) {
    const nodeType = step.stepDetailDTO?.nodeType;
    if (nodeType) {
      mapping[step.stepId] = nodeType;
    }
  }
  return mapping;
};

// ============ Hook 实现 ============

const useMultiRoleRun = (trainTaskId: string | null) => {
  const [batch, setBatch] = useState<MultiRoleRunBatch | null>(null);
  const [isBatchAutoRunning, setIsBatchAutoRunning] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const batchRef = useRef<MultiRoleRunBatch | null>(null);
  const stepNodeTypeByIdRef = useRef<Record<string, ScriptNodeType>>({});
  const autoRunActiveRef = useRef(false);
  const autoRunTokenRef = useRef(0);
  const isLoadingRef = useRef(false);

  useEffect(() => {
    batchRef.current = batch;
  }, [batch]);

  useEffect(() => {
    isLoadingRef.current = isLoading;
  }, [isLoading]);

  // trainTaskId 变化时整批重置
  useEffect(() => {
    if (batchRef.current && trainTaskId !== batchRef.current.trainTaskId) {
      autoRunActiveRef.current = false;
      autoRunTokenRef.current += 1;
      setIsBatchAutoRunning(false);
      setBatch(null);
      batchRef.current = null;
      stepNodeTypeByIdRef.current = {};
      setIsLoading(false);
    }
  }, [trainTaskId]);

  const isMultiRoleMode = batch !== null;

  const updateRole = useCallback((roleIndex: number, updater: (role: RoleRunState) => RoleRunState) => {
    setBatch(prev => {
      if (!prev || roleIndex < 0 || roleIndex >= prev.roles.length) return prev;
      const updatedRoles = [...prev.roles];
      updatedRoles[roleIndex] = updater(updatedRoles[roleIndex]);
      const next = { ...prev, roles: updatedRoles };
      batchRef.current = next;
      return next;
    });
  }, []);

  const markRoleError = useCallback(
    (roleIndex: number, rawMessage: string, displayPrefix = '❌ 运行失败') => {
      const normalizedMessage = rawMessage.trim().length > 0 ? rawMessage.trim() : '未知错误';
      updateRole(roleIndex, role => ({
        ...addRoleMessage(role, 'system', `${displayPrefix}: ${normalizedMessage}`),
        workflowState: 'ERROR' as WorkflowState,
        error: normalizedMessage,
      }));
    },
    [updateRole],
  );

  const isTerminalStepId = useCallback((stepId: string) => stepNodeTypeByIdRef.current[stepId] === 'SCRIPT_END', []);

  const updateBatchState = useCallback(() => {
    setBatch(prev => {
      if (!prev) return prev;
      const allDone = prev.roles.every(r => r.workflowState === 'COMPLETED' || r.workflowState === 'ERROR');
      const anyRunning = prev.roles.some(
        r => r.workflowState !== 'COMPLETED' && r.workflowState !== 'ERROR' && r.workflowState !== 'IDLE',
      );
      let batchState = prev.batchState;
      if (allDone) batchState = 'COMPLETED';
      else if (anyRunning) batchState = 'RUNNING';
      const next = { ...prev, batchState };
      batchRef.current = next;
      return next;
    });
  }, []);

  const appendLogEntry = useCallback(async (logSessionId: string | null, entry: AgentLogEntry) => {
    if (!logSessionId) return;
    try {
      await agentLogStorage.addEntry(logSessionId, entry);
    } catch {
      console.warn('⚠️ 多角色日志写入失败');
    }
  }, []);

  /**
   * 为指定角色执行 runCard，获取 sessionId 和首条 AI 消息
   */
  const runCardForRole = useCallback(
    async (
      roleIndex: number,
      stepId: string,
      sessionOverride?: string | null,
    ): Promise<{ completed: boolean; nextStepId?: string; cancelled?: boolean }> => {
      const currentBatch = batchRef.current;
      if (!currentBatch || !trainTaskId) return { completed: false, cancelled: true };
      const role = currentBatch.roles[roleIndex];
      if (!role) return { completed: false, cancelled: true };

      if (isTerminalStepId(stepId)) {
        updateRole(roleIndex, r =>
          addRoleMessage(
            {
              ...r,
              currentStepId: stepId,
              workflowState: 'COMPLETED' as WorkflowState,
            },
            'system',
            '✅ 训练已完成！',
            false,
            stepId,
          ),
        );
        return { completed: true };
      }

      updateRole(roleIndex, r => ({ ...r, workflowState: 'RUNNING_CARD' as WorkflowState }));

      const runCardRequestPayload = {
        endpoint: API_ENDPOINTS.RUN_CARD,
        method: 'POST' as const,
        body: {
          taskId: trainTaskId,
          stepId,
          sessionId: sessionOverride ?? role.sessionId ?? undefined,
        },
      };

      let runCardResponse: ApiResponse<RunCardResponse>;
      try {
        runCardResponse = await apiRequest<ApiResponse<RunCardResponse>>(runCardRequestPayload);
      } catch (error) {
        if (!shouldRetryRequestError(error)) {
          throw error;
        }

        await sleep(MULTI_ROLE_RETRY_DELAY_MS);
        runCardResponse = await apiRequest<ApiResponse<RunCardResponse>>(runCardRequestPayload);
      }

      if (!runCardResponse?.data?.sessionId) {
        throw new Error('启动对话失败：未返回 sessionId');
      }

      const newSessionId = runCardResponse.data.sessionId;
      const stepName = stepId;

      updateRole(roleIndex, r => {
        let updated: RoleRunState = {
          ...r,
          sessionId: newSessionId,
          currentStepId: stepId,
          workflowState: 'CHATTING' as WorkflowState,
        };

        if (runCardResponse.data.text) {
          updated = addRoleMessage(updated, 'assistant', runCardResponse.data.text, false, stepId);
        }

        return updated;
      });

      if (runCardResponse.data.text) {
        await appendLogEntry(role.logSessionId, {
          type: 'chat',
          timestamp: Date.now(),
          stepId,
          stepName,
          round: role.dialogueRound,
          source: 'runCard',
          aiText: runCardResponse.data.text,
        });
      }

      // 处理跳步
      if (runCardResponse.data.needSkipStep && runCardResponse.data.nextStepId) {
        const nextStepId = runCardResponse.data.nextStepId;
        if (isTerminalStepId(nextStepId)) {
          updateRole(roleIndex, r =>
            addRoleMessage(
              { ...r, currentStepId: nextStepId, workflowState: 'COMPLETED' },
              'system',
              '✅ 训练已完成！',
            ),
          );
          return { completed: true };
        }
        updateRole(roleIndex, r => addRoleMessage(r, 'system', `进入下一个阶段——${nextStepId}`));
        return runCardForRole(roleIndex, nextStepId, newSessionId);
      }

      return { completed: false };
    },
    [trainTaskId, updateRole, appendLogEntry, isTerminalStepId],
  );

  /**
   * 为指定角色执行一轮自动对话（生成回答 → 发送 → 处理响应）
   */
  const autoGenerateForRole = useCallback(
    async (roleIndex: number): Promise<{ needConfig: boolean; completed: boolean }> => {
      const currentBatch = batchRef.current;
      if (!currentBatch || !trainTaskId) return { needConfig: false, completed: false };

      const role = currentBatch.roles[roleIndex];
      if (role.workflowState !== 'CHATTING' || !role.sessionId || !role.currentStepId) {
        return { needConfig: false, completed: false };
      }

      const lastAssistant = [...role.messages].reverse().find(m => m.role === 'assistant');
      if (!lastAssistant) return { needConfig: false, completed: false };

      // 构建对话历史
      const conversationHistory: Array<{ ai: string; student: string }> = [];
      for (let i = 0; i < role.messages.length - 1; i++) {
        if (role.messages[i].role === 'assistant' && role.messages[i + 1]?.role === 'user') {
          conversationHistory.push({
            ai: role.messages[i].content,
            student: role.messages[i + 1].content,
          });
        }
      }

      // 调用 LLM 生成（传入角色 profile override）
      const llmResult = await generateStudentAnswer(lastAssistant.content, conversationHistory, {
        profile: role.profile,
      });

      if (!llmResult.success) {
        if (llmResult.error?.includes('请先配置')) {
          updateRole(roleIndex, r => addRoleMessage(r, 'system', '⚠️ 请先配置 LLM API Key'));
          return { needConfig: true, completed: false };
        }
        updateRole(roleIndex, r => addRoleMessage(r, 'system', `❌ 生成失败: ${llmResult.error}`));
        return { needConfig: false, completed: false };
      }

      const generatedAnswer = llmResult.content!;

      // 显示生成的回答
      updateRole(roleIndex, r => addRoleMessage(r, 'user', generatedAnswer, true, role.currentStepId!));

      // 发送到服务器
      let response: ApiResponse<ChatResponse>;
      try {
        response = await apiRequest<ApiResponse<ChatResponse>>({
          endpoint: API_ENDPOINTS.CHAT,
          method: 'POST',
          body: {
            taskId: trainTaskId,
            stepId: role.currentStepId,
            text: generatedAnswer,
            sessionId: role.sessionId,
          },
        });
      } catch (error) {
        if (!shouldRetryRequestError(error)) {
          throw error;
        }

        // 遇可重试错误重试一次
        await sleep(MULTI_ROLE_RETRY_DELAY_MS);
        try {
          response = await apiRequest<ApiResponse<ChatResponse>>({
            endpoint: API_ENDPOINTS.CHAT,
            method: 'POST',
            body: {
              taskId: trainTaskId,
              stepId: role.currentStepId,
              text: generatedAnswer,
              sessionId: role.sessionId,
            },
          });
        } catch (retryErr) {
          markRoleError(roleIndex, (retryErr as Error).message, '❌ 发送失败');
          return { needConfig: false, completed: false };
        }
      }

      const data = response?.data;
      const nextRound = role.dialogueRound + 1;

      updateRole(roleIndex, r => ({ ...r, dialogueRound: nextRound }));

      if (data) {
        await appendLogEntry(role.logSessionId, {
          type: 'chat',
          timestamp: Date.now(),
          stepId: role.currentStepId!,
          round: nextRound,
          source: 'chat',
          userText: generatedAnswer,
          aiText: data.text ?? undefined,
        });
      }

      // 检查完成
      if (data?.text == null && data?.nextStepId == null) {
        updateRole(roleIndex, r => addRoleMessage({ ...r, workflowState: 'COMPLETED' }, 'system', '✅ 训练已完成！'));
        return { needConfig: false, completed: true };
      }

      if (data?.text) {
        updateRole(roleIndex, r => addRoleMessage(r, 'assistant', data.text!, false, role.currentStepId!));
      }

      // 需要跳步
      if (data?.nextStepId) {
        if (isTerminalStepId(data.nextStepId)) {
          updateRole(roleIndex, r =>
            addRoleMessage(
              { ...r, currentStepId: data.nextStepId ?? null, workflowState: 'COMPLETED' },
              'system',
              '✅ 训练已完成！',
            ),
          );
          return { needConfig: false, completed: true };
        }

        updateRole(roleIndex, r => addRoleMessage(r, 'system', `进入下一个阶段——${data.nextStepId}`));
        try {
          const runResult = await runCardForRole(roleIndex, data.nextStepId!, role.sessionId);
          if (runResult.cancelled) {
            return { needConfig: false, completed: false };
          }
          return { needConfig: false, completed: runResult.completed };
        } catch (error) {
          markRoleError(roleIndex, (error as Error).message, '❌ 跳转步骤失败');
          return { needConfig: false, completed: false };
        }
      }

      return { needConfig: false, completed: false };
    },
    [trainTaskId, updateRole, appendLogEntry, runCardForRole, markRoleError, isTerminalStepId],
  );

  // ============ 公开 API ============

  const startMultiRoleRun = useCallback(
    async (drafts: RoleRunDraft[]) => {
      if (!trainTaskId || drafts.length === 0) return;

      setIsLoading(true);

      try {
        // 读取全局配置获取完整 profile 对象
        const config = await llmConfigStorage.get();
        const profileMap = new Map(config.studentProfiles.map(p => [p.id, p]));

        // 获取任务名称
        let taskName = '';
        try {
          const configResponse = await apiRequest<ApiResponse<TrainConfigurationResponse>>({
            endpoint: API_ENDPOINTS.QUERY_CONFIGURATION,
            method: 'POST',
            body: { trainTaskId },
          });
          taskName = configResponse?.data?.trainTaskName?.trim() || '';
        } catch {
          console.warn('⚠️ 获取训练任务名称失败');
        }
        const displayName = taskName || `${trainTaskId.substring(0, 8)}...`;

        // 获取步骤列表 + flowList
        const [stepsResponse, flowResponse] = await Promise.all([
          apiRequest<ApiResponse<ScriptStepItem[]>>({
            endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_LIST,
            method: 'POST',
            body: { trainTaskId, trainSubType: 'ability' },
          }),
          apiRequest<ApiResponse<ScriptStepFlow[]>>({
            endpoint: API_ENDPOINTS.QUERY_SCRIPT_STEP_FLOW_LIST,
            method: 'POST',
            body: { trainTaskId },
          }).catch(
            () =>
              ({
                code: 200,
                message: '',
                data: [],
              }) as ApiResponse<ScriptStepFlow[]>,
          ),
        ]);

        const steps = stepsResponse?.data ?? [];
        if (!steps.length) throw new Error('获取步骤列表失败');

        const flows = flowResponse?.data ?? [];
        const orderedStepIds = resolveOrderedNodeStepIds(steps, flows);
        const firstStepId = resolveFirstStepId(steps, flows);
        if (!firstStepId) throw new Error('无法确定首个训练步骤');

        const stepMapping = buildStepNameMapping(steps);
        stepNodeTypeByIdRef.current = buildStepNodeTypeMapping(steps);
        const batchId = generateId();

        // 为每个角色创建 run state 和 log session
        const roles: RoleRunState[] = [];
        for (const draft of drafts) {
          const profile = profileMap.get(draft.profileId);
          if (!profile) continue;

          const logSessionName = `${displayName}-${draft.profileLabel}-${batchId.substring(0, 4)}`;
          let logSessionId: string | null = null;

          try {
            const session = await agentLogStorage.createSession({
              taskId: trainTaskId,
              taskName: logSessionName,
              stepNameMapping: stepMapping,
            });
            logSessionId = session.id;
          } catch {
            console.warn(`⚠️ 角色 ${draft.profileLabel} 日志初始化失败`);
          }

          const roleState = createRoleRunState(draft, profile);
          roleState.logSessionId = logSessionId;
          roles.push(roleState);
        }

        if (!roles.length) throw new Error('没有有效的角色可运行');

        const newBatch: MultiRoleRunBatch = {
          batchId,
          trainTaskId,
          roles,
          activeRoleIndex: 0,
          batchState: 'RUNNING',
          orderedStepIds,
        };
        setBatch(newBatch);
        batchRef.current = newBatch;

        // 依次为每个角色启动 runCard（串行，间隔 500ms）
        for (let i = 0; i < roles.length; i++) {
          updateRole(i, r =>
            addRoleMessage(r, 'system', `正在启动步骤: ${stepMapping[firstStepId] ?? firstStepId}...`),
          );

          try {
            const result = await runCardForRole(i, firstStepId);
            if (result.cancelled) {
              break;
            }
            updateRole(i, r => ({
              ...r,
              dialogueRound: 1,
              ...(result.completed ? {} : {}),
            }));

            if (!result.completed) {
              updateRole(i, r => addRoleMessage(r, 'system', '对话已开始'));
            }
          } catch (err) {
            markRoleError(i, (err as Error).message, '❌ 启动失败');
          }

          if (i < roles.length - 1) {
            await sleep(MULTI_ROLE_POLL_INTERVAL_MS);
          }
        }

        updateBatchState();
      } catch (err) {
        setBatch(prev => {
          if (!prev) return prev;
          const next = { ...prev, batchState: 'ERROR' as const };
          batchRef.current = next;
          return next;
        });
        console.error('多角色启动失败:', err);
      } finally {
        setIsLoading(false);
      }
    },
    [trainTaskId, updateRole, runCardForRole, updateBatchState, markRoleError],
  );

  const setActiveRoleIndex = useCallback((index: number) => {
    setBatch(prev => {
      if (!prev || index < 0 || index >= prev.roles.length) return prev;
      const next = { ...prev, activeRoleIndex: index };
      batchRef.current = next;
      return next;
    });
  }, []);

  const sendToActiveRole = useCallback(
    async (content: string) => {
      const currentBatch = batchRef.current;
      if (!currentBatch || !trainTaskId) return;

      // 手动发送先停掉 batch auto-run
      if (autoRunActiveRef.current) {
        autoRunActiveRef.current = false;
        autoRunTokenRef.current += 1;
        setIsBatchAutoRunning(false);
      }

      const roleIndex = currentBatch.activeRoleIndex;
      const role = currentBatch.roles[roleIndex];
      if (!role || role.workflowState !== 'CHATTING' || !role.sessionId || !role.currentStepId) return;

      setIsLoading(true);
      updateRole(roleIndex, r => addRoleMessage(r, 'user', content, false));

      try {
        const response = await apiRequest<ApiResponse<ChatResponse>>({
          endpoint: API_ENDPOINTS.CHAT,
          method: 'POST',
          body: {
            taskId: trainTaskId,
            stepId: role.currentStepId,
            text: content,
            sessionId: role.sessionId,
          },
        });

        const data = response?.data;
        const nextRound = role.dialogueRound + 1;
        updateRole(roleIndex, r => ({ ...r, dialogueRound: nextRound }));

        if (data) {
          await appendLogEntry(role.logSessionId, {
            type: 'chat',
            timestamp: Date.now(),
            stepId: role.currentStepId!,
            round: nextRound,
            source: 'chat',
            userText: content,
            aiText: data.text ?? undefined,
          });
        }

        if (data?.text == null && data?.nextStepId == null) {
          updateRole(roleIndex, r => addRoleMessage({ ...r, workflowState: 'COMPLETED' }, 'system', '✅ 训练已完成！'));
        } else {
          if (data?.text) {
            updateRole(roleIndex, r => addRoleMessage(r, 'assistant', data.text!));
          }
          if (data?.nextStepId) {
            if (isTerminalStepId(data.nextStepId)) {
              updateRole(roleIndex, r =>
                addRoleMessage(
                  { ...r, currentStepId: data.nextStepId ?? null, workflowState: 'COMPLETED' },
                  'system',
                  '✅ 训练已完成！',
                ),
              );
            } else {
              updateRole(roleIndex, r => addRoleMessage(r, 'system', `进入下一个阶段——${data.nextStepId}`));
              await runCardForRole(roleIndex, data.nextStepId!, role.sessionId);
            }
          }
        }

        updateBatchState();
      } catch (err) {
        updateRole(roleIndex, r => addRoleMessage(r, 'system', `❌ 发送失败: ${(err as Error).message}`));
      } finally {
        setIsLoading(false);
      }
    },
    [trainTaskId, updateRole, appendLogEntry, runCardForRole, updateBatchState, isTerminalStepId],
  );

  const startBatchAutoRun = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (autoRunActiveRef.current || !batchRef.current) return { needConfig: false };

    autoRunActiveRef.current = true;
    autoRunTokenRef.current += 1;
    const token = autoRunTokenRef.current;
    setIsBatchAutoRunning(true);

    let needConfig = false;

    try {
      while (autoRunActiveRef.current && token === autoRunTokenRef.current) {
        const currentBatch = batchRef.current;
        if (!currentBatch) break;
        if (currentBatch.roles.every(role => isRoleTerminalState(role.workflowState))) break;

        // 找到下一个还在 CHATTING 状态的角色（round-robin）
        let ranAny = false;
        for (let i = 0; i < currentBatch.roles.length; i++) {
          if (!autoRunActiveRef.current || token !== autoRunTokenRef.current) break;

          const role = currentBatch.roles[i];
          if (role.workflowState !== 'CHATTING') continue;

          if (isLoadingRef.current) {
            await sleep(300);
            continue;
          }

          setIsLoading(true);
          try {
            const result = await autoGenerateForRole(i);
            if (result.needConfig) {
              needConfig = true;
              autoRunActiveRef.current = false;
              break;
            }
            ranAny = true;
          } catch (error) {
            markRoleError(i, (error as Error).message, '❌ 自动运行失败');
          } finally {
            setIsLoading(false);
          }

          await sleep(MULTI_ROLE_POLL_INTERVAL_MS);
        }

        if (needConfig) break;

        updateBatchState();

        // 如果没有任何角色能运行，检查是否全部结束
        const finalBatch = batchRef.current;
        if (!finalBatch || finalBatch.roles.every(role => isRoleTerminalState(role.workflowState))) {
          break;
        }
        if (!ranAny) {
          await sleep(MULTI_ROLE_POLL_INTERVAL_MS);
        }
      }
    } catch (error) {
      console.error('多角色自动运行异常:', error);
    } finally {
      if (token === autoRunTokenRef.current) {
        autoRunActiveRef.current = false;
      }
      setIsBatchAutoRunning(false);
      updateBatchState();
    }

    return { needConfig };
  }, [autoGenerateForRole, updateBatchState, markRoleError]);

  const stopBatchAutoRun = useCallback(() => {
    if (!autoRunActiveRef.current) return;
    autoRunActiveRef.current = false;
    autoRunTokenRef.current += 1;
    setIsBatchAutoRunning(false);
  }, []);

  const resetMultiRole = useCallback(() => {
    autoRunActiveRef.current = false;
    autoRunTokenRef.current += 1;
    setIsBatchAutoRunning(false);
    setBatch(null);
    batchRef.current = null;
    stepNodeTypeByIdRef.current = {};
    setIsLoading(false);
  }, []);

  return {
    batch,
    isMultiRoleMode,
    isLoading,
    isBatchAutoRunning,
    startMultiRoleRun,
    stopMultiRoleRun: resetMultiRole,
    sendToActiveRole,
    setActiveRoleIndex,
    startBatchAutoRun,
    stopBatchAutoRun,
    resetMultiRole,
  };
};

export { useMultiRoleRun };
