/**
 * 能力训练 Pro（trainV2）状态机 Hook
 * 协议与防死锁机制移植自 auto_train_pro.py（HAR 实测验证）。
 * 独立于 useAgentChat / useVoiceAgentChat，不共享运行时状态。
 */

import { generateStudentAnswer } from '../services/llm-service';
import { fetchPolymasUserInfo } from '../services/polymas-user-service';
import { buildStudentAnswerInput, formatProLogEntry } from '../services/pro-conversation';
import { fetchProTrainingContext, toStagePromptContext } from '../services/pro-training-context-service';
import { resolveTrainingMetadata } from '../services/training-metadata-service';
import { TrainV2Client } from '../services/ws/train-v2-client';
import { agentLogStorage, llmConfigStorage } from '@extension/storage';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { ProTurn } from '../services/pro-conversation';
import type { ProTrainingContext, ProStagePromptContext } from '../services/pro-training-context-service';
import type { TrainV2Handlers } from '../services/ws/train-v2-client';

// 对齐 useAgentChat 的 ChatMessage 字段，追加 Pro 特有的角色昵称标签
interface ProMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
  modelId?: string;
  roleLabel?: string;
}

type ProState = 'IDLE' | 'CONNECTING' | 'RUNNING' | 'COMPLETED' | 'ERROR';
type ProTurnPhase = 'WAITING_BOT' | 'USER_TURN' | 'STAGE_ENTRY';

// ============ 协议常量（auto_train_pro.py 实测值，不做用户可配置项） ============
const STAGE_ENTRY_TEXT = '好的';
const STAGE_ENTRY_MAX_TRIES = 12;
// 每次开场应答后最多等多久判定「本阶段已启动」；需大于服务端首角色规划耗时（实测约 37s）
const STAGE_ENTRY_TIMEOUT_MS = 60_000;
// 连续安静该时长（无任何事件/音频帧）才发开场应答，否则会被 continueSuperseded 拒绝
const STAGE_ENTRY_QUIET_MS = 2_500;
const POLL_INTERVAL_MS = 500;
// 全自动轮数上限，防失控刷 LLM
const MAX_AUTO_TURNS = 40;
const PRO_CONTEXT_UNAVAILABLE_MESSAGE = '⚠️ 未获取到 Pro 训练上下文，AI 作答暂不可用，可手动作答或重试';

const sleep = (ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms));

const generateId = () => `pro_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;

// 对齐脚本 session_id：21 位 URL-safe 随机串
const generateWsSessionId = (): string => {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '')
    .slice(0, 21);
};

const useProAgentChat = (trainTaskId: string | null) => {
  const [proState, setProStateRaw] = useState<ProState>('IDLE');
  const [turnPhase, setTurnPhaseRaw] = useState<ProTurnPhase>('WAITING_BOT');
  const [messages, setMessages] = useState<ProMessage[]>([]);
  const [stepIndex, setStepIndex] = useState(0);
  const [round, setRound] = useState(0);
  const [currentRoleNickname, setCurrentRoleNickname] = useState<string | null>(null);
  const [isAutoRunning, setIsAutoRunning] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const clientRef = useRef<TrainV2Client | null>(null);
  const proStateRef = useRef<ProState>('IDLE');
  const turnPhaseRef = useRef<ProTurnPhase>('WAITING_BOT');
  const turnsRef = useRef<ProTurn[]>([]);
  const logSessionIdRef = useRef<string | null>(null);
  const stepIdRef = useRef<string | null>(null);
  const stepIndexRef = useRef(0);
  const roundRef = useRef(0);
  const autoRunRef = useRef(false);
  const currentRoleRef = useRef<{ nid: string; nickname: string } | null>(null);
  const botSpokeRef = useRef(false);
  const supersededRef = useRef(false);
  const stageEntryRunningRef = useRef(false);
  const proContextRef = useRef<ProTrainingContext | null>(null);
  const proContextErrorRef = useRef(false);
  // 会话代际号：teardown 后递增，使旧会话遗留的异步循环立即退出
  const runSeqRef = useRef(0);

  // 状态写入同时同步 ref，避免 WS 回调读到过期值（事件到达早于 useEffect 同步）
  const setProState = useCallback((next: ProState) => {
    proStateRef.current = next;
    setProStateRaw(next);
  }, []);

  const setTurnPhase = useCallback((next: ProTurnPhase) => {
    turnPhaseRef.current = next;
    setTurnPhaseRaw(next);
  }, []);

  useEffect(() => {
    autoRunRef.current = isAutoRunning;
  }, [isAutoRunning]);

  const addMessage = useCallback(
    (
      role: ProMessage['role'],
      content: string,
      opts?: { roleLabel?: string; isAutoGenerated?: boolean; modelId?: string },
    ) => {
      const message: ProMessage = {
        id: generateId(),
        role,
        content,
        timestamp: Date.now(),
        stepId: stepIdRef.current ?? undefined,
        isAutoGenerated: opts?.isAutoGenerated,
        modelId: opts?.modelId,
        roleLabel: opts?.roleLabel,
      };
      setMessages(prev => [...prev, message]);
    },
    [],
  );

  const appendLog = useCallback(async (turn: ProTurn) => {
    const sessionId = logSessionIdRef.current;
    if (!sessionId) {
      return;
    }
    try {
      await agentLogStorage.addEntry(sessionId, {
        type: 'chat',
        timestamp: Date.now(),
        stepId: stepIdRef.current ?? 'unknown',
        stepName: `阶段 ${stepIndexRef.current}`,
        round: roundRef.current,
        source: 'chat',
        ...formatProLogEntry(turn),
      });
    } catch (err) {
      console.warn('[pro] append log failed', err);
    }
  }, []);

  // 记录一条对话轮次：入 LLM 上下文 + 聊天气泡 + 历史日志（增量写，错误中断也不丢已发生对话）
  const recordTurn = useCallback(
    (turn: ProTurn, opts?: { isAutoGenerated?: boolean; modelId?: string }) => {
      turnsRef.current = [...turnsRef.current, turn];
      const role = turn.role === 'user' ? 'user' : turn.role === 'coach' ? 'system' : 'assistant';
      addMessage(role, turn.content, {
        roleLabel: turn.role === 'user' ? undefined : turn.label,
        isAutoGenerated: opts?.isAutoGenerated,
        modelId: opts?.modelId,
      });
      void appendLog(turn);
    },
    [addMessage, appendLog],
  );

  const teardown = useCallback(() => {
    runSeqRef.current += 1;
    autoRunRef.current = false;
    setIsAutoRunning(false);
    setIsGenerating(false);
    stageEntryRunningRef.current = false;
    if (clientRef.current) {
      clientRef.current.close();
      clientRef.current = null;
    }
  }, []);

  // 正常收尾（scriptEnd / 手动停止 / 全自动上限）：界面回到空闲态样式，可直接重新开始
  const endRun = useCallback(
    (notice: string) => {
      addMessage('system', notice);
      setProState('COMPLETED');
      setTurnPhase('WAITING_BOT');
      teardown();
    },
    [addMessage, setProState, setTurnPhase, teardown],
  );

  const failRun = useCallback(
    (message: string) => {
      setError(message);
      addMessage('system', `❌ ${message}`);
      setProState('ERROR');
      setTurnPhase('WAITING_BOT');
      teardown();
    },
    [addMessage, setProState, setTurnPhase, teardown],
  );

  const isRunningSeq = useCallback((seq: number) => runSeqRef.current === seq && proStateRef.current === 'RUNNING', []);

  const submitStudentText = useCallback(
    (text: string, opts?: { isAutoGenerated?: boolean; modelId?: string }) => {
      const client = clientRef.current;
      const trimmed = text.trim();
      if (!client || !trimmed || proStateRef.current !== 'RUNNING') {
        return;
      }
      roundRef.current += 1;
      setRound(roundRef.current);
      recordTurn({ role: 'user', label: '你(学生)', content: trimmed }, opts);
      // 协议：学生回合 = userTextInput + 恰好一次 continueCurrentStep
      client.sendEvent('userTextInput', { text: trimmed });
      client.sendEvent('continueCurrentStep');
      setTurnPhase('WAITING_BOT');
    },
    [recordTurn, setTurnPhase],
  );

  const sendStudentText = useCallback(
    (text: string) => {
      submitStudentText(text);
    },
    [submitStudentText],
  );

  const generateAndSend = useCallback(
    async (seq: number): Promise<{ needConfig: boolean; ok: boolean }> => {
      const config = await llmConfigStorage.get();
      if (!config.apiKey) {
        return { needConfig: true, ok: false };
      }
      if (proContextErrorRef.current) {
        addMessage('system', PRO_CONTEXT_UNAVAILABLE_MESSAGE);
        return { needConfig: false, ok: false };
      }
      setIsGenerating(true);
      try {
        const { aiQuestion, history } = buildStudentAnswerInput(turnsRef.current);
        const ctx = proContextRef.current;
        let proContext: ProStagePromptContext | undefined;
        if (ctx) {
          const stage = stepIdRef.current ? ctx.stagesById.get(stepIdRef.current) : undefined;
          if (stage) {
            proContext = toStagePromptContext(stage, ctx.taskName, ctx.taskDescription);
          } else {
            // 阶段缺失：降级用任务级上下文（buildProContextSections 会只产出「实训任务」段）
            console.warn('[pro] 当前阶段不在上下文缓存中，降级用任务级上下文', stepIdRef.current);
            proContext = {
              taskName: ctx.taskName,
              taskDescription: ctx.taskDescription,
              stepName: '',
              stepDescription: '',
              llmPrompt: '',
              studentRole: { roleName: '', assignName: '', description: '' },
              participantRoles: [],
            };
          }
        }
        const result = await generateStudentAnswer(aiQuestion, history, proContext ? { proContext } : undefined);
        if (!isRunningSeq(seq) || turnPhaseRef.current !== 'USER_TURN') {
          return { needConfig: false, ok: false };
        }
        if (!result.success || !result.content || !result.content.trim()) {
          setError(result.error ?? 'AI 生成失败');
          addMessage('system', `⚠️ AI 生成失败：${result.error ?? '未知错误'}，请手动输入或重试`);
          return { needConfig: false, ok: false };
        }
        submitStudentText(result.content, { isAutoGenerated: true, modelId: config.model });
        return { needConfig: false, ok: true };
      } finally {
        setIsGenerating(false);
      }
    },
    [addMessage, isRunningSeq, submitStudentText],
  );

  // 全自动路径：上限触发即主动结束；LLM 失败自动暂停退回半交互（不静默发兜底假答案）
  const autoAnswer = useCallback(
    async (seq: number) => {
      if (roundRef.current >= MAX_AUTO_TURNS) {
        endRun(`⏹ 已达全自动上限（${MAX_AUTO_TURNS} 轮），训练已自动结束`);
        return;
      }
      const result = await generateAndSend(seq);
      if (!result.ok) {
        autoRunRef.current = false;
        setIsAutoRunning(false);
        if (result.needConfig) {
          addMessage('system', '⚠️ 请先配置 LLM API Key，再使用 AI 作答');
        }
      }
    },
    [addMessage, endRun, generateAndSend],
  );

  const waitQuiet = useCallback(
    async (seq: number) => {
      for (;;) {
        const client = clientRef.current;
        if (!client || !isRunningSeq(seq)) {
          return;
        }
        const prev = client.activitySeq;
        await sleep(STAGE_ENTRY_QUIET_MS);
        if ((clientRef.current?.activitySeq ?? prev) === prev) {
          return;
        }
      }
    },
    [isRunningSeq],
  );

  /**
   * 非首阶段开场应答（脚本 _handle_stage_entry 的移植）：
   * stepStart 后服务端停在 selectRoleStart 等学生先应答一句，否则本阶段永久卡死。
   * 过早发送会被 continueSuperseded 拒绝，故：等安静 → 发「好的」→ 等 botAnswerStart；
   * 被拒或超时则重试，最多 STAGE_ENTRY_MAX_TRIES 次。
   * 开场应答是协议解锁动作而非教学回合，半交互与全自动一律自动发送。
   */
  const runStageEntry = useCallback(
    async (seq: number) => {
      if (stageEntryRunningRef.current) {
        return;
      }
      stageEntryRunningRef.current = true;
      try {
        setTurnPhase('STAGE_ENTRY');
        roundRef.current += 1;
        setRound(roundRef.current);
        recordTurn({ role: 'user', label: '你(学生)', content: STAGE_ENTRY_TEXT }, { isAutoGenerated: true });
        for (let attempt = 1; attempt <= STAGE_ENTRY_MAX_TRIES; attempt++) {
          await waitQuiet(seq);
          if (!isRunningSeq(seq)) {
            return;
          }
          botSpokeRef.current = false;
          supersededRef.current = false;
          clientRef.current?.sendEvent('userTextInput', { text: STAGE_ENTRY_TEXT });
          clientRef.current?.sendEvent('continueCurrentStep');
          let waited = 0;
          while (waited < STAGE_ENTRY_TIMEOUT_MS) {
            if (botSpokeRef.current) {
              setTurnPhase('WAITING_BOT');
              return;
            }
            if (supersededRef.current) {
              break;
            }
            if (!isRunningSeq(seq)) {
              return;
            }
            await sleep(POLL_INTERVAL_MS);
            waited += POLL_INTERVAL_MS;
          }
        }
        failRun('阶段开场多次重试仍未启动本阶段（服务端可能异常）');
      } finally {
        stageEntryRunningRef.current = false;
      }
    },
    [failRun, isRunningSeq, recordTurn, setTurnPhase, waitQuiet],
  );

  const autoGenerate = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (proStateRef.current !== 'RUNNING' || turnPhaseRef.current !== 'USER_TURN') {
      return { needConfig: false };
    }
    const result = await generateAndSend(runSeqRef.current);
    return { needConfig: result.needConfig };
  }, [generateAndSend]);

  const startAutoRun = useCallback(async (): Promise<{ needConfig: boolean }> => {
    const config = await llmConfigStorage.get();
    if (!config.apiKey) {
      return { needConfig: true };
    }
    autoRunRef.current = true;
    setIsAutoRunning(true);
    if (proStateRef.current === 'RUNNING' && turnPhaseRef.current === 'USER_TURN') {
      void autoAnswer(runSeqRef.current);
    }
    return { needConfig: false };
  }, [autoAnswer]);

  const stopAutoRun = useCallback(() => {
    autoRunRef.current = false;
    setIsAutoRunning(false);
  }, []);

  const start = useCallback(async () => {
    if (!trainTaskId) {
      setError('未找到训练任务ID，请在训练页面打开');
      return;
    }
    if (clientRef.current || proStateRef.current === 'CONNECTING' || proStateRef.current === 'RUNNING') {
      return;
    }
    const seq = runSeqRef.current + 1;
    runSeqRef.current = seq;
    setMessages([]);
    turnsRef.current = [];
    stepIdRef.current = null;
    stepIndexRef.current = 0;
    setStepIndex(0);
    roundRef.current = 0;
    setRound(0);
    currentRoleRef.current = null;
    setCurrentRoleNickname(null);
    setError(null);
    stageEntryRunningRef.current = false;
    setProState('CONNECTING');
    setTurnPhase('WAITING_BOT');
    addMessage('system', '正在获取用户信息...');

    proContextRef.current = null;
    proContextErrorRef.current = false;
    try {
      const [userInfo, trainingMeta] = await Promise.all([fetchPolymasUserInfo(), resolveTrainingMetadata()]);
      let taskDisplayName = trainTaskId;
      try {
        const proContext = await fetchProTrainingContext(trainTaskId);
        if (runSeqRef.current !== seq) {
          return;
        }
        proContextRef.current = proContext;
        if (proContext.taskName) {
          taskDisplayName = proContext.taskName;
        }
      } catch (ctxError) {
        if (runSeqRef.current !== seq) {
          return;
        }
        proContextErrorRef.current = true;
        console.warn('[pro] 训练上下文获取失败', ctxError);
        addMessage('system', PRO_CONTEXT_UNAVAILABLE_MESSAGE);
      }

      const config = await llmConfigStorage.get();
      const profile = config.studentProfiles.find(p => p.id === config.studentProfileId) ?? config.studentProfiles[0];
      const profileLabel = profile?.label?.trim() || '学生';
      try {
        const session = await agentLogStorage.createSession({
          taskId: trainTaskId,
          taskName: `${taskDisplayName}-${profileLabel}-Pro`,
          trainingMeta,
          stepNameMapping: {},
        });
        logSessionIdRef.current = session.id;
      } catch (logError) {
        console.warn('[pro] 日志初始化失败', logError);
      }

      addMessage('system', `训练任务：${taskDisplayName}`);

      const handlers: TrainV2Handlers = {
        onConnected: payload => {
          console.log('[pro] connected', payload.connectType);
        },
        onNextStep: payload => {
          stepIdRef.current = payload.nextStepId;
          stepIndexRef.current += 1;
          setStepIndex(stepIndexRef.current);
          clientRef.current?.sendEvent('stepStart', { stepId: payload.nextStepId });
          // 首阶段由 scriptStart 自动开场；非首阶段需学生开场应答，否则永久卡死
          if (stepIndexRef.current >= 2) {
            void runStageEntry(seq);
          }
        },
        onSelectRoleEnd: payload => {
          if (payload.roleNid === 'user') {
            currentRoleRef.current = null;
            setCurrentRoleNickname(null);
            setTurnPhase('USER_TURN');
            if (autoRunRef.current) {
              void autoAnswer(seq);
            }
          } else {
            currentRoleRef.current = {
              nid: payload.roleNid,
              nickname: payload.roleNickname ?? payload.roleName ?? '对方',
            };
            setCurrentRoleNickname(currentRoleRef.current.nickname);
            setTurnPhase('WAITING_BOT');
          }
        },
        onBotAnswerStart: () => {
          // 有角色开口 = 本阶段已启动（供阶段开场重试判定成功）
          botSpokeRef.current = true;
        },
        onBotAnswerEnd: payload => {
          const nid = payload.roleNid ?? currentRoleRef.current?.nid ?? '';
          const nickname = payload.roleNickname ?? currentRoleRef.current?.nickname ?? '对方';
          if (nid === 'system') {
            recordTurn({ role: 'coach', label: '教练点评', content: payload.content });
          } else {
            recordTurn({ role: 'bot', label: nickname, content: payload.content });
          }
          // 协议：每个角色回合结束发恰好一次 continueCurrentStep
          clientRef.current?.sendEvent('continueCurrentStep');
        },
        onContinueSuperseded: () => {
          supersededRef.current = true;
        },
        onScriptEnd: () => {
          endRun('🎉 训练完成！');
        },
        onServerError: payload => {
          failRun(`服务端错误：${JSON.stringify(payload)}`);
        },
        onClose: () => {
          if (proStateRef.current === 'RUNNING' || proStateRef.current === 'CONNECTING') {
            failRun('连接已断开');
          }
        },
      };

      const client = new TrainV2Client(
        { taskId: trainTaskId, userId: userInfo.userId, sessionId: generateWsSessionId() },
        handlers,
      );
      clientRef.current = client;
      await client.connect();
      if (runSeqRef.current !== seq) {
        client.close();
        return;
      }
      setProState('RUNNING');
      addMessage('system', '连接成功，剧本已启动，等待角色分配...');
    } catch (err) {
      clientRef.current = null;
      // 运行代际已推进（onClose 已 failRun，或用户 stop/reset/卸载）：跳过重复/覆盖性的 failRun
      if (runSeqRef.current !== seq) {
        return;
      }
      failRun(err instanceof Error ? err.message : '连接失败');
    }
  }, [trainTaskId, addMessage, autoAnswer, endRun, failRun, recordTurn, runStageEntry, setProState, setTurnPhase]);

  const stop = useCallback(() => {
    if (proStateRef.current !== 'RUNNING' && proStateRef.current !== 'CONNECTING') {
      return;
    }
    endRun('⏹ 已手动停止训练');
  }, [endRun]);

  const reset = useCallback(() => {
    teardown();
    setProState('IDLE');
    setTurnPhase('WAITING_BOT');
    setMessages([]);
    turnsRef.current = [];
    stepIdRef.current = null;
    stepIndexRef.current = 0;
    setStepIndex(0);
    roundRef.current = 0;
    setRound(0);
    currentRoleRef.current = null;
    setCurrentRoleNickname(null);
    setError(null);
    logSessionIdRef.current = null;
    proContextRef.current = null;
    proContextErrorRef.current = false;
  }, [setProState, setTurnPhase, teardown]);

  // 组件卸载时断开连接
  useEffect(
    () => () => {
      clientRef.current?.close();
      clientRef.current = null;
    },
    [],
  );

  return {
    proState,
    turnPhase,
    messages,
    stepIndex,
    round,
    currentRoleNickname,
    isAutoRunning,
    isGenerating,
    error,
    start,
    stop,
    sendStudentText,
    autoGenerate,
    startAutoRun,
    stopAutoRun,
    reset,
  };
};

export { useProAgentChat };
export type { ProState, ProTurnPhase, ProMessage };
