/**
 * 口语训练 Hook
 * 通过 WebSocket 接入 Polymas /ai-tools/ws/v2/trainFlow，把用户输入或 AI 自动生成的
 * 文本合成 TTS 音频后以 PCM 帧发送，服务端回复文本流渲染为聊天气泡。
 */

import { buildAudioFrames, buildSilenceFrame, SILENCE_TAIL_COUNT } from '../services/audio/frame-builder';
import { mp3ToPcm16k } from '../services/audio/pcm-codec';
import { synthesizeTTS } from '../services/audio/tts-client';
import {
  apiRequest,
  API_ENDPOINTS,
  extractTrainTaskId,
  getCurrentTabUrl,
  onTabUrlChanged,
} from '../services/background-bridge';
import { generateStudentAnswer } from '../services/llm-service';
import { fetchPolymasUserInfo, invalidatePolymasUserInfo } from '../services/polymas-user-service';
import { TrainingWsClient } from '../services/ws/training-ws-client';
import { agentLogStorage, agentSessionStorage, llmConfigStorage } from '@extension/storage';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { TrainingWsHandlers } from '../services/ws/training-ws-client';

// 对齐 useAgentChat 里的 ChatMessage，便于复用 MessageBubble / MessageList
interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
}

type VoiceState =
  | 'IDLE'
  | 'CONNECTING'
  | 'CONNECTED'
  | 'SENDING_AUDIO'
  | 'WAITING_SERVER'
  | 'BOT_SPEAKING'
  | 'COMPLETED'
  | 'ERROR';

const TRAINING_DOMAIN = 'hike-teaching-center.polymas.com';
const FRAME_INTERVAL_MS = 100;

const sleep = (ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms));

const generateId = () => `voice_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;

interface TrainConfigurationResponse {
  trainTaskName?: string;
}

interface ApiResponse<T> {
  code: number;
  message: string;
  data: T;
}

const fetchTrainTaskName = async (taskId: string): Promise<string | null> => {
  try {
    const response = await apiRequest<ApiResponse<TrainConfigurationResponse>>({
      endpoint: API_ENDPOINTS.QUERY_CONFIGURATION,
      method: 'POST',
      body: { trainTaskId: taskId },
    });
    const name = response?.data?.trainTaskName?.trim();
    return name && name.length > 0 ? name : null;
  } catch (error) {
    console.warn('[voice] 获取 trainTaskName 失败', error);
    return null;
  }
};

const useVoiceAgentChat = () => {
  const [trainTaskId, setTrainTaskId] = useState<string | null>(null);
  const [trainTaskName, setTrainTaskName] = useState<string | null>(null);
  const [voiceState, setVoiceState] = useState<VoiceState>('IDLE');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dialogueRound, setDialogueRound] = useState(0);
  const [isAutoRunning, setIsAutoRunning] = useState(false);

  const wsRef = useRef<TrainingWsClient | null>(null);
  const sessionIdRef = useRef<string | null>(null);
  const stepIdRef = useRef<string | null>(null);
  const stepNameRef = useRef<string>('');
  const trainTaskIdRef = useRef<string | null>(null);
  const trainTaskNameRef = useRef<string | null>(null);
  const stepJustStartedRef = useRef(false);
  const pendingUserTextRef = useRef<string | null>(null);
  const draftBotRef = useRef<string>('');
  const botOpenRef = useRef(false);
  const activeLogSessionIdRef = useRef<string | null>(null);
  const currentAbortRef = useRef<AbortController | null>(null);
  const audioDrainResolveRef = useRef<(() => void) | null>(null);
  const isTaskCompleteRef = useRef(false);
  const dialogueRoundRef = useRef(0);
  const voiceStateRef = useRef<VoiceState>('IDLE');
  const autoRunActiveRef = useRef(false);
  const autoRunTokenRef = useRef(0);
  const isLoadingRef = useRef(false);
  // true 表示上一条 bot 回复已 finalize，等着用户（或 auto-run）回应
  const awaitingUserReplyRef = useRef(false);
  // 绕过 useCallback 闭包陷阱：auto-run 循环里拿最新 messages
  const messagesRef = useRef<ChatMessage[]>([]);

  useEffect(() => {
    trainTaskIdRef.current = trainTaskId;
  }, [trainTaskId]);

  useEffect(() => {
    trainTaskNameRef.current = trainTaskName;
  }, [trainTaskName]);

  useEffect(() => {
    dialogueRoundRef.current = dialogueRound;
  }, [dialogueRound]);

  useEffect(() => {
    voiceStateRef.current = voiceState;
  }, [voiceState]);

  useEffect(() => {
    isLoadingRef.current = isLoading;
  }, [isLoading]);

  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  const addMessage = useCallback(
    (role: ChatMessage['role'], content: string, opts?: { isAutoGenerated?: boolean; stepId?: string }) => {
      const message: ChatMessage = {
        id: generateId(),
        role,
        content,
        timestamp: Date.now(),
        stepId: opts?.stepId ?? stepIdRef.current ?? undefined,
        isAutoGenerated: opts?.isAutoGenerated,
      };
      setMessages(prev => [...prev, message]);
      return message;
    },
    [],
  );

  const appendLog = useCallback(
    async (entry: {
      source: 'runCard' | 'chat';
      userText?: string;
      aiText?: string;
      stepId?: string;
      round: number;
    }) => {
      const sessionId = activeLogSessionIdRef.current;
      if (!sessionId) {
        return;
      }
      try {
        await agentLogStorage.addEntry(sessionId, {
          type: 'chat',
          timestamp: Date.now(),
          stepId: entry.stepId ?? stepIdRef.current ?? 'unknown',
          stepName: stepNameRef.current || (entry.stepId ?? stepIdRef.current ?? 'unknown'),
          round: entry.round,
          source: entry.source,
          userText: entry.userText,
          aiText: entry.aiText,
        });
      } catch (err) {
        console.warn('[voice] append log failed', err);
      }
    },
    [],
  );

  const finalizeBotDraft = useCallback(
    async (reason: string, clearDraft: boolean) => {
      const hadOpen = botOpenRef.current;
      const draft = draftBotRef.current;
      if (draft) {
        const source: 'runCard' | 'chat' = stepJustStartedRef.current ? 'runCard' : 'chat';
        addMessage('assistant', draft, { stepId: stepIdRef.current ?? undefined });
        await appendLog({
          source,
          userText: source === 'chat' ? (pendingUserTextRef.current ?? undefined) : undefined,
          aiText: draft,
          stepId: stepIdRef.current ?? undefined,
          round: dialogueRoundRef.current,
        });
        pendingUserTextRef.current = null;
        if (stepJustStartedRef.current) {
          stepJustStartedRef.current = false;
        }
        // Bot 刚说完一段有效内容，轮到学生回应
        awaitingUserReplyRef.current = true;
      }
      botOpenRef.current = false;
      if (clearDraft) {
        draftBotRef.current = '';
      }
      if (hadOpen || draft) {
        console.log(`[voice] bot draft finalized: ${reason}`);
      }
    },
    [addMessage, appendLog],
  );

  const requestAbort = useCallback((reason: string) => {
    if (currentAbortRef.current) {
      currentAbortRef.current.abort(new Error(reason));
    }
  }, []);

  const resolveAudioDrain = useCallback(() => {
    if (audioDrainResolveRef.current) {
      audioDrainResolveRef.current();
      audioDrainResolveRef.current = null;
    }
  }, []);

  const cleanup = useCallback(() => {
    requestAbort('cleanup');
    resolveAudioDrain();
    if (wsRef.current) {
      wsRef.current.close();
      wsRef.current = null;
    }
  }, [requestAbort, resolveAudioDrain]);

  const startSession = useCallback(async () => {
    const taskId = trainTaskIdRef.current;
    if (!taskId) {
      setError('未找到训练任务ID，请确保在正确的页面打开');
      return;
    }
    if (wsRef.current) {
      return;
    }

    setError(null);
    setIsLoading(true);
    setVoiceState('CONNECTING');
    addMessage('system', '正在获取用户信息...');

    try {
      const [userInfo, resolvedTaskName] = await Promise.all([fetchPolymasUserInfo(), fetchTrainTaskName(taskId)]);
      const taskDisplayName = resolvedTaskName || trainTaskNameRef.current || taskId;
      if (resolvedTaskName && resolvedTaskName !== trainTaskNameRef.current) {
        setTrainTaskName(resolvedTaskName);
      }

      const config = await llmConfigStorage.get();
      const profile = config.studentProfiles.find(p => p.id === config.studentProfileId) ?? config.studentProfiles[0];
      const profileLabel = profile?.label?.trim() || '学生';

      try {
        const session = await agentLogStorage.createSession({
          taskId,
          taskName: `${taskDisplayName}-${profileLabel}-口语`,
          stepNameMapping: {},
        });
        activeLogSessionIdRef.current = session.id;
      } catch (logError) {
        console.warn('[voice] 日志初始化失败', logError);
      }

      addMessage('system', `训练任务：${taskDisplayName}`);
      addMessage('system', '正在建立语音通道...');

      const handlers: TrainingWsHandlers = {
        onConnected: payload => {
          sessionIdRef.current = payload.sessionId;
          stepIdRef.current = payload.stepId;
          stepNameRef.current = payload.stepName || payload.stepId;
          stepJustStartedRef.current = true;
          setVoiceState('CONNECTED');
          addMessage('system', `会话建立 · 当前步骤：${stepNameRef.current}`);
          wsRef.current?.sendEvent('startScript', {
            sessionId: null,
            userId: userInfo.userId,
            taskId,
            schoolId: userInfo.schoolId,
            stepId: payload.stepId,
          });
        },
        onBotAnswerStart: () => {
          if (botOpenRef.current) {
            void finalizeBotDraft('new botAnswerStart', true);
          }
          botOpenRef.current = true;
          draftBotRef.current = '';
          setVoiceState('BOT_SPEAKING');
          requestAbort('botAnswerStart');
        },
        onBotAnswer: p => {
          draftBotRef.current += p.msg ?? '';
        },
        onBotAnswerEnd: () => {
          void finalizeBotDraft('botAnswerEnd', false).then(() => {
            draftBotRef.current = '';
            setVoiceState('CONNECTED');
          });
        },
        onUserTextStart: () => {
          if (botOpenRef.current && stepJustStartedRef.current) {
            void finalizeBotDraft('userTextStart', true);
          }
        },
        onUserText: p => {
          console.log('[voice] ASR partial:', p.text);
        },
        onUserTextEnd: p => {
          const text = p.text ?? '';
          setDialogueRound(prev => prev + 1);
          pendingUserTextRef.current = text;
          if (botOpenRef.current) {
            void finalizeBotDraft('userTextEnd', true).then(() => {
              pendingUserTextRef.current = text;
            });
          }
        },
        onUserAudioEnd: () => {
          requestAbort('userAudioEnd');
        },
        onStepEnd: payload => {
          const nextStepId = payload.nextStepId;
          const nextStepName = payload.nextStepName || payload.stepName || nextStepId || '未知';
          if (botOpenRef.current) {
            void finalizeBotDraft('stepEnd', true);
          }
          requestAbort('stepEnd');
          if (nextStepId) {
            stepIdRef.current = nextStepId;
            stepNameRef.current = nextStepName;
            stepJustStartedRef.current = true;
            pendingUserTextRef.current = null;
            addMessage('system', `进入下一个阶段——${nextStepName}`);
            const drainPromise = new Promise<void>(resolve => {
              audioDrainResolveRef.current = resolve;
            });
            Promise.race([drainPromise, sleep(2000)]).finally(() => {
              wsRef.current?.sendEvent('nextStep', { stepId: nextStepId });
            });
          } else {
            isTaskCompleteRef.current = true;
            setVoiceState('COMPLETED');
            addMessage('system', '✅ 训练已完成');
          }
        },
        onScriptEnd: () => {
          if (botOpenRef.current) {
            void finalizeBotDraft('scriptEnd', true);
          }
          requestAbort('scriptEnd');
          isTaskCompleteRef.current = true;
          setVoiceState('COMPLETED');
          addMessage('system', '🎉 剧本已完成');
        },
        onTaskEnd: () => {
          requestAbort('taskEnd');
          isTaskCompleteRef.current = true;
          setVoiceState('COMPLETED');
          addMessage('system', '🎉 任务已结束');
        },
        onError: payload => {
          console.warn('[voice] server error', payload);
          requestAbort('server error');
          setVoiceState('ERROR');
          const text = typeof payload === 'object' && payload ? JSON.stringify(payload).slice(0, 200) : String(payload);
          addMessage('system', `⚠️ 服务端错误：${text}`);
        },
        onClose: ev => {
          resolveAudioDrain();
          if (!isTaskCompleteRef.current && voiceStateRef.current !== 'IDLE') {
            addMessage('system', `语音通道已关闭 (code=${ev.code})`);
          }
        },
      };

      const client = new TrainingWsClient(taskId, handlers);
      wsRef.current = client;
      await client.connect();
      setDialogueRound(0);
    } catch (err) {
      setVoiceState('ERROR');
      setError((err as Error).message);
      addMessage('system', `错误: ${(err as Error).message}`);
      if (wsRef.current) {
        wsRef.current.close();
        wsRef.current = null;
      }
      // 若是权限/会话问题，强制下一次重新获取
      invalidatePolymasUserInfo();
    } finally {
      setIsLoading(false);
    }
  }, [addMessage, finalizeBotDraft, requestAbort, resolveAudioDrain]);

  const sendAudioFrames = useCallback(async (frames: Uint8Array[], signal: AbortSignal) => {
    const ws = wsRef.current;
    if (!ws) {
      throw new Error('WebSocket 未连接');
    }
    for (const frame of frames) {
      if (signal.aborted) {
        return false;
      }
      if (!ws.sendBinary(frame)) {
        return false;
      }
      await sleep(FRAME_INTERVAL_MS);
    }
    const silence = buildSilenceFrame();
    for (let i = 0; i < SILENCE_TAIL_COUNT; i += 1) {
      if (signal.aborted) {
        return false;
      }
      if (!ws.sendBinary(silence)) {
        return false;
      }
      await sleep(FRAME_INTERVAL_MS);
    }
    return true;
  }, []);

  const sendUserText = useCallback(
    async (text: string, opts?: { isAutoGenerated?: boolean }) => {
      const ws = wsRef.current;
      if (!ws) {
        addMessage('system', '请先建立语音通道');
        return;
      }
      if (isTaskCompleteRef.current) {
        return;
      }
      const trimmed = text.trim();
      if (!trimmed) {
        return;
      }

      // 停止上一轮还在进行的发送
      requestAbort('new turn');
      const controller = new AbortController();
      currentAbortRef.current = controller;
      // 本轮开始回应 Bot，清除"等待学生回复"标志
      awaitingUserReplyRef.current = false;

      setIsLoading(true);
      addMessage('user', trimmed, { isAutoGenerated: opts?.isAutoGenerated });

      try {
        setVoiceState('SENDING_AUDIO');
        const mp3 = await synthesizeTTS(trimmed, { signal: controller.signal });
        if (controller.signal.aborted) {
          return;
        }
        const pcm = await mp3ToPcm16k(mp3);
        if (controller.signal.aborted) {
          return;
        }
        const frames = buildAudioFrames(pcm);
        const completed = await sendAudioFrames(frames, controller.signal);
        resolveAudioDrain();
        if (completed && !controller.signal.aborted) {
          ws.sendEvent('mute', {});
          setVoiceState('WAITING_SERVER');
        }
      } catch (err) {
        if ((err as { name?: string }).name === 'AbortError') {
          return;
        }
        setVoiceState('ERROR');
        setError((err as Error).message);
        addMessage('system', `发送失败: ${(err as Error).message}`);
      } finally {
        if (currentAbortRef.current === controller) {
          currentAbortRef.current = null;
        }
        setIsLoading(false);
      }
    },
    [addMessage, requestAbort, resolveAudioDrain, sendAudioFrames],
  );

  const autoGenerate = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (!wsRef.current) {
      addMessage('system', '请先建立语音通道');
      return { needConfig: false };
    }
    // 从 ref 取最新 messages，避免 auto-run 循环闭包里拿到 stale 快照
    const currentMessages = messagesRef.current;
    let lastBot = '';
    const history: Array<{ ai: string; student: string }> = [];
    let pendingAi: string | null = null;
    for (const msg of currentMessages) {
      if (msg.role === 'assistant') {
        pendingAi = msg.content;
        lastBot = msg.content;
      } else if (msg.role === 'user' && pendingAi) {
        history.push({ ai: pendingAi, student: msg.content });
        pendingAi = null;
      }
    }
    if (!lastBot.trim()) {
      addMessage('system', '暂无 AI 提问，无法自动生成');
      return { needConfig: false };
    }
    setIsLoading(true);
    try {
      const result = await generateStudentAnswer(lastBot, history);
      if (!result.success) {
        if (result.error?.includes('API Key')) {
          return { needConfig: true };
        }
        addMessage('system', `AI 生成失败: ${result.error ?? '未知错误'}`);
        return { needConfig: false };
      }
      if (result.content) {
        await sendUserText(result.content, { isAutoGenerated: true });
      }
      return { needConfig: false };
    } finally {
      setIsLoading(false);
    }
  }, [addMessage, sendUserText]);

  const stopAutoRun = useCallback(() => {
    if (!autoRunActiveRef.current) {
      return;
    }
    autoRunActiveRef.current = false;
    autoRunTokenRef.current += 1;
    setIsAutoRunning(false);
  }, []);

  const startAutoRun = useCallback(async (): Promise<{ needConfig: boolean }> => {
    if (autoRunActiveRef.current) {
      return { needConfig: false };
    }
    if (!wsRef.current) {
      addMessage('system', '请先建立语音通道再开启全自动');
      return { needConfig: false };
    }
    if (isTaskCompleteRef.current) {
      return { needConfig: false };
    }

    autoRunActiveRef.current = true;
    autoRunTokenRef.current += 1;
    const token = autoRunTokenRef.current;
    setIsAutoRunning(true);

    let needConfig = false;

    while (autoRunActiveRef.current && token === autoRunTokenRef.current) {
      if (isTaskCompleteRef.current) {
        break;
      }
      const state = voiceStateRef.current;
      if (state === 'COMPLETED' || state === 'ERROR' || state === 'IDLE') {
        break;
      }
      // 只在 Bot 回复完（awaitingUserReplyRef=true）、且非正在处理时开始下一轮
      if (state !== 'CONNECTED' || isLoadingRef.current || !awaitingUserReplyRef.current) {
        await sleep(300);
        continue;
      }
      const result = await autoGenerate();
      if (result.needConfig) {
        needConfig = true;
        break;
      }
      await sleep(500);
    }

    if (token === autoRunTokenRef.current) {
      autoRunActiveRef.current = false;
    }
    setIsAutoRunning(false);
    return { needConfig };
  }, [addMessage, autoGenerate]);

  const reset = useCallback(() => {
    stopAutoRun();
    cleanup();
    sessionIdRef.current = null;
    stepIdRef.current = null;
    stepNameRef.current = '';
    stepJustStartedRef.current = false;
    pendingUserTextRef.current = null;
    draftBotRef.current = '';
    botOpenRef.current = false;
    activeLogSessionIdRef.current = null;
    isTaskCompleteRef.current = false;
    awaitingUserReplyRef.current = false;
    setMessages([]);
    setDialogueRound(0);
    setError(null);
    setIsLoading(false);
    setVoiceState('IDLE');
  }, [cleanup, stopAutoRun]);

  // 初始化 trainTaskId（复用 useAgentChat 的提取逻辑）
  useEffect(() => {
    let disposed = false;
    const init = async () => {
      const taskId = await extractTrainTaskId();
      if (disposed) return;
      if (taskId) {
        setTrainTaskId(taskId);
        try {
          await agentSessionStorage.updateTrainTaskId(taskId);
        } catch {
          // ignore
        }
        return;
      }
      const currentUrl = await getCurrentTabUrl();
      if (disposed) return;
      let isTrainingHost = false;
      if (currentUrl) {
        try {
          const parsedUrl = new URL(currentUrl);
          isTrainingHost = parsedUrl.hostname === TRAINING_DOMAIN;
        } catch {
          isTrainingHost = false;
        }
      }
      if (!isTrainingHost) {
        return;
      }
      try {
        const stored = await agentSessionStorage.get();
        if (!disposed && stored.trainTaskId?.trim()) {
          setTrainTaskId(stored.trainTaskId);
        }
      } catch {
        // ignore
      }
    };
    void init();

    const unsubscribe = onTabUrlChanged(async url => {
      if (!url.includes('trainTaskId=')) {
        return;
      }
      const taskId = await extractTrainTaskId(url);
      if (!disposed && taskId && taskId !== trainTaskIdRef.current) {
        setTrainTaskId(taskId);
        reset();
      }
    });

    return () => {
      disposed = true;
      unsubscribe();
    };
  }, [reset]);

  // 卸载时释放 WebSocket
  useEffect(() => () => cleanup(), [cleanup]);

  // 当 trainTaskId 变化时异步解析真实 taskName
  useEffect(() => {
    if (!trainTaskId) {
      setTrainTaskName(null);
      return;
    }
    let cancelled = false;
    void fetchTrainTaskName(trainTaskId).then(name => {
      if (!cancelled && name) {
        setTrainTaskName(name);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [trainTaskId]);

  return {
    trainTaskId,
    trainTaskName,
    voiceState,
    messages,
    isLoading,
    error,
    dialogueRound,
    isAutoRunning,
    startSession,
    sendUserText,
    autoGenerate,
    startAutoRun,
    stopAutoRun,
    reset,
  };
};

export { useVoiceAgentChat };
export type { ChatMessage as VoiceChatMessage, VoiceState };
