import { cn } from '../../utils.js';

export interface MessageBubbleProps {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: number;
  isAutoGenerated?: boolean;
}

export const MessageBubble = ({ role, content, timestamp, isAutoGenerated }: MessageBubbleProps) => {
  const isUser = role === 'user';
  const isSystem = role === 'system';

  return (
    <div className={cn('mb-3 flex w-full', isUser ? 'justify-end' : 'justify-start')}>
      <div
        className={cn(
          'max-w-[80%] rounded-2xl px-4 py-2 shadow-sm',
          isUser
            ? 'rounded-br-md bg-blue-500 text-white'
            : isSystem
              ? 'bg-gray-200 text-sm italic text-gray-600'
              : 'rounded-bl-md border border-gray-200 bg-white text-gray-800',
        )}>
        {/* 角色标识 */}
        <div className={cn('mb-1 text-xs font-medium', isUser ? 'text-blue-100' : 'text-gray-500')}>
          {isUser ? '👤 你' : isSystem ? '📢 系统' : '🤖 AI助手'}
          {isAutoGenerated && <span className="ml-1 opacity-70">(自动生成)</span>}
        </div>

        {/* 消息内容 */}
        <div className="whitespace-pre-wrap break-words">{content}</div>

        {/* 时间戳 */}
        {timestamp && (
          <div className={cn('mt-1 text-xs opacity-60', isUser ? 'text-right' : 'text-left')}>
            {new Date(timestamp).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}
          </div>
        )}
      </div>
    </div>
  );
};
