import { cn } from '../../utils.js';

export interface MessageBubbleProps {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: number;
  isAutoGenerated?: boolean;
}

export function MessageBubble({ role, content, timestamp, isAutoGenerated }: MessageBubbleProps) {
  const isUser = role === 'user';
  const isSystem = role === 'system';

  return (
    <div className={cn('flex w-full mb-3', isUser ? 'justify-end' : 'justify-start')}>
      <div
        className={cn(
          'max-w-[80%] rounded-2xl px-4 py-2 shadow-sm',
          isUser
            ? 'bg-blue-500 text-white rounded-br-md'
            : isSystem
              ? 'bg-gray-200 text-gray-600 text-sm italic'
              : 'bg-white text-gray-800 border border-gray-200 rounded-bl-md',
        )}>
        {/* 角色标识 */}
        <div className={cn('text-xs mb-1 font-medium', isUser ? 'text-blue-100' : 'text-gray-500')}>
          {isUser ? '👤 你' : isSystem ? '📢 系统' : '🤖 AI助手'}
          {isAutoGenerated && <span className="ml-1 opacity-70">(自动生成)</span>}
        </div>

        {/* 消息内容 */}
        <div className="whitespace-pre-wrap break-words">{content}</div>

        {/* 时间戳 */}
        {timestamp && (
          <div className={cn('text-xs mt-1 opacity-60', isUser ? 'text-right' : 'text-left')}>
            {new Date(timestamp).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}
          </div>
        )}
      </div>
    </div>
  );
}
