import { MessageBubble } from './MessageBubble.js';
import { cn } from '../../utils.js';
import { useRef, useEffect } from 'react';
import type { MessageBubbleProps } from './MessageBubble.js';

export interface Message extends MessageBubbleProps {
  id: string;
}

export interface MessageListProps {
  messages: Message[];
  isLoading?: boolean;
  className?: string;
}

export const MessageList = ({ messages, isLoading = false, className }: MessageListProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  // 自动滚动到底部
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages.length]);

  return (
    <div ref={containerRef} className={cn('flex-1 overflow-y-auto bg-gray-50 p-4', className)}>
      {messages.length === 0 ? (
        <div className="flex h-full flex-col items-center justify-center text-gray-400">
          <div className="mb-2 text-4xl">💬</div>
          <div className="text-sm">暂无消息</div>
          <div className="mt-1 text-xs">点击开始按钮开启对话</div>
        </div>
      ) : (
        <>
          {messages.map(message => (
            <MessageBubble
              key={message.id}
              role={message.role}
              content={message.content}
              timestamp={message.timestamp}
              isAutoGenerated={message.isAutoGenerated}
            />
          ))}

          {/* 加载指示器 */}
          {isLoading && (
            <div className="mb-3 flex justify-start">
              <div className="rounded-2xl rounded-bl-md border border-gray-200 bg-white px-4 py-3 shadow-sm">
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 animate-bounce rounded-full bg-gray-400" style={{ animationDelay: '0ms' }} />
                  <div
                    className="h-2 w-2 animate-bounce rounded-full bg-gray-400"
                    style={{ animationDelay: '150ms' }}
                  />
                  <div
                    className="h-2 w-2 animate-bounce rounded-full bg-gray-400"
                    style={{ animationDelay: '300ms' }}
                  />
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {/* 滚动锚点 */}
      <div ref={bottomRef} />
    </div>
  );
};
