/**
 * 智能体对话消息存储
 */

import { createStorage, StorageEnum } from '../base/index.js';
import type { BaseStorageType } from '../base/index.js';
// 类型定义 - 避免循环依赖，在此处内联定义
export type MessageRole = 'user' | 'assistant' | 'system';

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: number;
  stepId?: string;
  isAutoGenerated?: boolean;
}

const STORAGE_KEY_AGENT_CHAT = 'agent-chat-messages';

const DEFAULT_MESSAGES: ChatMessage[] = [];

const storage = createStorage<ChatMessage[]>(STORAGE_KEY_AGENT_CHAT, DEFAULT_MESSAGES, {
  storageEnum: StorageEnum.Local,
  liveUpdate: true,
});

export interface AgentChatStorageType extends BaseStorageType<ChatMessage[]> {
  addMessage: (message: Omit<ChatMessage, 'id' | 'timestamp'>) => Promise<ChatMessage>;
  clearMessages: () => Promise<void>;
  getMessagesByStepId: (stepId: string) => Promise<ChatMessage[]>;
  getLastMessage: () => Promise<ChatMessage | null>;
}

// 生成唯一ID
const generateId = (): string => {
  return `msg_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
};

export const agentChatStorage: AgentChatStorageType = {
  ...storage,

  addMessage: async (message: Omit<ChatMessage, 'id' | 'timestamp'>): Promise<ChatMessage> => {
    const newMessage: ChatMessage = {
      ...message,
      id: generateId(),
      timestamp: Date.now(),
    };

    await storage.set(current => [...current, newMessage]);
    return newMessage;
  },

  clearMessages: async () => {
    await storage.set([]);
  },

  getMessagesByStepId: async (stepId: string): Promise<ChatMessage[]> => {
    const messages = await storage.get();
    return messages.filter(msg => msg.stepId === stepId);
  },

  getLastMessage: async (): Promise<ChatMessage | null> => {
    const messages = await storage.get();
    return messages.length > 0 ? messages[messages.length - 1] : null;
  },
};
